### ISSUE TITLE
[nemo-preview] Execution as a non-privileged user fails

### ISSUE THREAD

**Issue by theSeppi** [linuxmint/nemo-extensions#100]
I accidentally started nemo-preview from a root instance of nemo. Afterwards I wasn't able to use as a normal user any more.

By executing nemo-preview from a terminal, I managed to get the following exceptions as soon as I hit enter in an nemo instance opened after it:

```
(nemo-preview-start:4334): GStreamer-CRITICAL **: gst_date_time_new: assertion 'year > 0 && year <= 9999' failed

(nemo-preview-start:4334): GStreamer-CRITICAL **: gst_date_time_unref: assertion 'datetime != NULL' failed

(nemo-preview-start:4334): GStreamer-CRITICAL **: gst_date_time_new: assertion 'year > 0 && year <= 9999' failed

(nemo-preview-start:4334): GStreamer-CRITICAL **: gst_date_time_unref: assertion 'datetime != NULL' failed
Segmentation fault
```

At the same time dmesg reports the following:

```
[ 3647.529193] traps: nemo-preview-st[4490] general protection ip:7f1cb2a3747b sp:7fffefdc4790 error:0 in libc-2.19.so[7f1cb29b8000+1bb000]
```

How can I fix this? I already reinstalled nemo-preview multiple times, but without any effect.

**Comment by leigh123linux** [comment]
If you can reproduce the issue with 3.4 version feel free to reopen.
