### ISSUE TITLE
Package python-simplejson should be listed as a dependency for nemo-rabbitvcs

### ISSUE THREAD

**Issue by achmafooma** [linuxmint/nemo-extensions#106]
Installed nemo-rabbitvcs in Mint 17.1 Cinnamon edition, and it didn't work. The error that appeared when launching Nemo from the command line was "No module named simplejson."

Upon installing package python-simplejson, it worked fine. This leads me to believe that python-simplejson should be listed as a dependency for nemo-rabbitvcs.

The full error was as follows:

Traceback (most recent call last):
  File "/usr/share/nemo-python/extensions/RabbitVCS.py", line 85, in <module>
    import rabbitvcs.ui.property_page
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/ui/property_page.py", line 40, in <module>
    from rabbitvcs.services.checkerservice import StatusCheckerStub as StatusChecker
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/services/checkerservice.py", line 48, in <module>
    import simplejson
ImportError: *No module named simplejson*

**Comment by GLolol** [comment]
This would actually be an error in RabbitVCS's packaging, not nemo-rabbitvcs. I don't know how you obtained RabbitVCS, but Ubuntu 14.04's packaging (which Mint 17.x is based off of), includes it as a dependency already: http://packages.ubuntu.com/trusty/rabbitvcs-core

**Comment by achmafooma** [comment]
You're correct. Turns out my system was installing from GetDeb.net, which is where the dependency is missing. I will close this and report to the GetDeb folks. Thanks!
