### ISSUE TITLE
Memory leak and 100% CPU usage for unsupported SVN formats

### ISSUE THREAD

**Issue by crockeea** [linuxmint/nemo-extensions#109]
When I open an SVN directory in nemo with an unsupported svn format, nemo-rabbitvcs immediately takes 100% CPU and slowly eats memory until nemo crashes. I only managed to discover the issue by chance when I started nemo from the console and it printed the following message:

```
Initializing folder-color-switcher extension...
ERROR   rabbitvcs.vcs.svn   The working copy at '/.../mysvndir'
is too old (format 29) to work with client version '1.8.8 (r1568071)' (expects format 31). You need to upgrade the working copy first.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/vcs/svn/__init__.py", line 254, in statuses
    update=update)
ClientError: The working copy at '/.../mysvndir'
is too old (format 29) to work with client version '1.8.8 (r1568071)' (expects format 31). You need to upgrade the working copy first.
```

If I navigate out of the old svn directory, CPU usage drops, but nemo continues to eat memory until it dies. Upgrading the svn format of the directory solved the problem.

**Comment by Vahan86** [comment]
@crockeea, is this still an issue for you with nemo-rabbitvcs 3.2?

**Comment by crockeea** [comment]
I haven't used it in quite a while now.

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
