### ISSUE TITLE
[Regression][nemo-terminal][2.6.5] Terminal no longer changes dir on changing nemo folders

### ISSUE THREAD

**Issue by gauravjuvekar** [linuxmint/nemo-extensions#113]
Happened after upgrading nemo from romeo
````
$ apt version nemo
2.6.5+rafaela
$ apt version nemo-terminal
2.4.0+rebecca
$ apt version cinnamon
2.6.7+rafaela
````

**Comment by UberPanda** [comment]
Hey man,

Got the same problem here on 2.6.5.

I looked into the python code (/usr/share/nemo-python/extensions/nemo_terminal.py)
nemo terminal only changes directory when the terminal is not busy :

line 234 :    if not self._shell_is_busy():

But apparently what happens is the terminal is, for some reason, always considered busy. An quick and ugly kludge is to comment the line 234 "if not self._shell_is_busy():".

I am currently looking into the _shell_is_busy method to figure out what is wrong with it ...

**Comment by mtwebster** [comment]
No issue here - are you guys running a non-standard shell, or have something in your .bashrc that could be causing this?  Take a look at `ps auxf` - see if anything is attached.

**Comment by UberPanda** [comment]
I got gnome-pty-helper attached with 2 /bin/bash (dual panel nemo).

FYI my bashrc is a mess

**Comment by UberPanda** [comment]
Ok I figured it out : 
- Clearing bashrc did not help

- On kernel 3.13, it works fine, but not on 3.19 (and 4.05 on archlinux btw). I think something changed in the way wchan is handled sometimes between those two kernels.

Made a quick fix to take the wait_woken and do_wait in account : 
https://github.com/UberPanda/Stuff/blob/09bf32031fe7761fe8ec634f0ac69e36e9090e74/nemo-terminal/nemo_terminal.py

(line 344-347) but I am not sure if the rest of the _shell_is_busy method is actually still relevant.

**Comment by skualos** [comment]
The fix from UberPanda worked for me on Ubuntu 15.04 (using nemo from Webupd8 ppa)

**Comment by benwiley4000** [comment]
Hm, that fix did NOT work for me unfortunately...on Ubuntu MATE 15.04 with nemo 2.6.7 and nemo-terminal 2.6.0

**Comment by kendoori** [comment]
Fix worked for me on Mint 17.2 Cinnamon (Nemo 2.6.7)/Kernel 3.19. I am noticing a lag in the execution of the changing folders, along with a history of the prior locations (I don't think that happened before)...

**Comment by UberPanda** [comment]
benwiley4000 : What kernel are you using ? I haven't used it on anything else than mint and manjaro but I don't think ubuntu mate would be any different.

**Comment by benwiley4000** [comment]
UberPanda: 3.19.0-28-generic

**Comment by kendoori** [comment]
I noticed that since I added UberPanda's patch that the terminal panel opens every time that I open Nemo. Is there a way for to change the behavior so that it opens normally?

**Comment by UberPanda** [comment]
kendoori : I believe what you describe is the normal nemo-terminal behavior. Just untick it in the nemo plugin menu if you don't want it to start. I don't have any lag on my end so it may come from something else.

benwiley4000 : Yep, that's the unpatched behavior. Just tried on Mate and it worked fine. Don't know what to tell you. Could you paste the output of launching nemo from terminal and moving though folders ? Are you sure you applied the patch properly ?

**Comment by kendoori** [comment]
@UberPanda turns out that there's a dconf setting for the default opening behavior as noted here: 
https://github.com/linuxmint/nemo-extensions/issues/57

![selection_066](https://cloud.githubusercontent.com/assets/2447420/10219787/fa96fe5c-680f-11e5-956a-8310e3964c51.png)

Toggling this setting off, does open Nemo w/o terminal open, but allows for F4 to open it.
