### ISSUE TITLE
Change python for python2

### ISSUE THREAD

**Issue by Salamandar** [linuxmint/nemo-extensions#128]
Hi ! I'm using nemo-compare on ArchLinux.
python links to python3.
Nemo-compare does not start (module gtk not found (this is python2 gtk library)).
You should replace the first line

```
#!/usr/bin/python
```

by 

```
#!/usr/bin/python2
```

:)

**Comment by alium** [comment]
This is problem inside Archlinux, not nemo or LinuxMint. This is no bug, but 'feature'. See:
https://www.archlinux.org/news/python-is-now-python-3/. You should use in PKGBUILD for nemo or cinnamon: 
 # Python2 fix
  find -type f | xargs sed -i 's@^#!.*python$@#!/usr/bin/python2@'

Another distributions use another python2/3 rules. Should by close, NO BUG.

**Comment by Salamandar** [comment]
Most seem fixed.
