### ISSUE TITLE
SUGGESTION - Extract to folder -

### ISSUE THREAD

**Issue by robinpecha** [linuxmint/nemo-extensions#132]
Hello,
I think that the whole world would have been happy for the plugin Extract archive to folder ... not only basic Extract here.
The most commonly I want to unpack the archive somewhere. Not to view the content.

Another issue, viewing archives causes pre-extracting them to a cache. In case of several Gigs files ...

Big thanks to coders .)
Robin

**Comment by DVeris** [comment]
+1

**Comment by DVeris** [comment]
for example
myarchive.zip

extract in myarchive
extract here

**Comment by leigh123linux** [comment]
'Extract to' is already included


![2017-04-23-082436_3840x2160_scrot](https://cloud.githubusercontent.com/assets/1299302/25311642/8c5b6648-27fe-11e7-9db4-78d586cd1171.png)
