### ISSUE TITLE
nemo terminal doesn't follow directory

### ISSUE THREAD

**Issue by jrversteegh** [linuxmint/nemo-extensions#137]
The nemo terminal doesn't follow the selected directory. I have two mint rafaela installs. It works on one and not the other. No message indicating any trouble appears when nemo is started from the command line. I very much like this feature, so I would like to get it to work, but I have no idea of how to proceed. 
I've looked at org.nemo.extension.nemo-terminal.default-folllow-mode and it says "Terminal follows Nemo".

**Comment by jrversteegh** [comment]
I see this issue has already been fixed in here, just not in mint.

**Comment by 211217613** [comment]
What do you mean it has been fixed here but not in mint? Do you mean MINT isn't using the most up to date nemo-terminal?

**Comment by EduardDopler** [comment]
This is a duplicate of some other issues (don't want to reference them, use the search).
Linux Mint isn't a rolling release, so *no*, Mint doesn't always have the most up-to-date software. You can see in the [repository](http://packages.linuxmint.com/search.php?keyword=nemo-terminal&release=any&section=any) which Mint version offers which nemo-terminal version.

**Comment by jrversteegh** [comment]
@211217613 Yes, that's what I mean.
@EduardDopler I know which version of nemo-terminal is installed.
