### ISSUE TITLE
nemo-share depends on apturl, making it uninstallable on stock Debian

### ISSUE THREAD

**Issue by GLolol** [linuxmint/nemo-extensions#146]
Nemo-share includes [quite a bit of code for checking](https://github.com/linuxmint/nemo-extensions/blob/468f76062e155e1a6f611e3cf94e787922118a02/nemo-share/src/nemo-share.c#L586-L818) whether Samba is installed, and tries to install it via `apturl` if missing. However, apturl is not available in stock Debian, making a built package uninstallable there.

Since nemo-extensions is already using Debian-style packages, I don't think the Samba installation part is necessary: why not just add the things it installs as dependencies? However, the logging out and logging back in screen should probably be kept, unless it isn't needed anymore. (GLolol/nemo-extensions@ef1a78e45bc29f2077aa4efd29de119e8c8973f8 is an incomplete fix, which strips out the auto-install code entirely.)

**Comment by EduardDopler** [comment]
In what terms is your fix incomplete?

**Comment by GLolol** [comment]
It removes the part that tells the user to log out and back in.

**Comment by EduardDopler** [comment]
In my opinion, it is okay to remove it from here as we're talking about the extension here. Such a check, if Samba itself is able to work correctly or not, should come with Samba.

**Comment by Norcoen** [comment]
you really should make a pull request, those dependencies and the samba check are insanely stupid^^

**Comment by GLolol** [comment]
Opened.
