### ISSUE TITLE
[nemo-preview] Incorrect texture alignment when Desktop UI scaling is HiDPI

### ISSUE THREAD

**Issue by hamiltont** [linuxmint/nemo-extensions#147]
Brand new 17.3 cinnamon installation on Lenovo W550s. Nemo preview works fine out of box, but my UI was all tiny, so I turned on `System Settings->General->Desktop Scaling->Double`. Nemo preview now looks like 

![this](https://i.imgur.com/KW0YTJGl.png)

Turning the desktop scaling back to normal fixes the issue. 

I've narrowed the problem down to incorrect alignment settings in `mainWindow.js`, specifically `_positionTexture`. If I manually set `yFactor=0` and also add an alignment constraint for X set to a factor 0, then nemo preview is working fine. [Here](https://gist.github.com/hamiltont/01d282c4034e0c900e2a) is a patch file, but I know this is not a robust solution (I didn't understand the maths happening in positionTexture, so I just ignored them in my patch...), but it does result in me having a working version of nemo-preview :-)

**Comment by leigh123linux** [comment]
Is this still an issue in 3.4 version?
