### ISSUE TITLE
[nemo-audio-tab]: add support for ogg files

### ISSUE THREAD

**Issue by robinpaulson** [linuxmint/nemo-extensions#150]
This would be much appreciated, I was impressed nautilus did it, surprised Nemo doesn't. I may have a look at doing it myself, if I knew you would accept patches and are pushed for time?

**Comment by EduardDopler** [comment]
Please note my [Pull Request] (https://github.com/linuxmint/nemo-extensions/pull/145). The new extension *nemo-media-tab* reads all kind of media files.
There is also a PPA for testing, if you do not want to build it yourself.

**Comment by robinpaulson** [comment]
Excellent, could you tell me where the PPA is? There are several associated with nemo.

**Comment by robinpaulson** [comment]
never mind, i found it
