### ISSUE TITLE
warning on installing python-nemo

### ISSUE THREAD

**Issue by robinpaulson** [linuxmint/nemo-extensions#152]
from https://launchpad.net/~garteneden/+archive/ubuntu/nemo-extensions

Linking libnemo-python.so in Nemo's extensiondir...ln: failed to create symbolic link ‘/usr/lib/i386-linux-gnu/nemo/extensions-3.0/libnemo-python.so’: No such file or directory
WARNING: libnemo-python.so might not be in the directory.

**Comment by EduardDopler** [comment]
As the version you used isn't officially included in nemo-extensions, please open an issue in the [user's repository] (https://github.com/EduardDopler/nemo-extensions), not here.

**Comment by robinpaulson** [comment]
Sure, or maybe could you ask yourself to come read this issue? ;-)

**Comment by EduardDopler** [comment]
@robinpaulson Please open a issue there and add your system information, like distro, architecture, which extensions do/don't work, what's the output when restarting nemo from command line etc.
