### ISSUE TITLE
[nemo-terminal] - Request - move terminal to bottom of nemo.

### ISSUE THREAD

**Issue by mlibre** [linuxmint/nemo-extensions#162]
is there any configuration file for this extension?
for example it's a good configuration feature that we can change terminal place.
or hide that with a shortcut.
thanks

**Comment by nurgasemetey** [comment]
I second that.

**Comment by dcrystalj** [comment]
this would be so nice

**Comment by fx-kirin** [comment]
`gsettings set org.nemo.extensions.nemo-terminal terminal-position 'bottom'`
 
It can move it to the bottom but there is a bug related with height.

https://github.com/linuxmint/nemo-extensions/issues/54

**Comment by M3cubo** [comment]
Is there a way to move the terminal to the bottom today? What should I put in the `nemo_terminal.py` file?

**Comment by leigh123linux** [comment]
![image](https://user-images.githubusercontent.com/1299302/186951348-709641c6-010c-4abc-8544-509d1f644690.png)
