### ISSUE TITLE
nemo-terminal cannot be installed

### ISSUE THREAD

**Issue by ph-laugier** [linuxmint/nemo-extensions#169]
Hi,

Trying to install nemo-terminal from synaptics gives:
Depends: gir1.2-vte-2.90 (>=1:0.34.6~) but it is not installable

**Comment by EduardDopler** [comment]
Although you included literally no information, I guess you're on Ubuntu xenial which shipps `gir1.2-vte-2.91` instead of 2.90. The latest nemo-terminal code is fixed to support the new version you use. So just install the new version **nemo-terminal 3.0.1**.

**Comment by leigh123linux** [comment]
I will mark this invalid and close due to lack of info.
