### ISSUE TITLE
Track in nemo-media-columns.

### ISSUE THREAD

**Issue by Pival81** [linuxmint/nemo-extensions#176]
When i add Track to the columns and sort by it, it shows this:
![screen01](https://cloud.githubusercontent.com/assets/15673222/18123702/58e3e0bc-6f6f-11e6-9341-e7c676d8770a.png)
It thinks that 10 is directly followed by 10, and that 2 is after 15.
I think that's pretty stupid.

**Comment by EduardDopler** [comment]
This is a libnautilus issue. It cannot be addressed with the nemo-extensions directly.

**Comment by marsjaninzmarsa** [comment]
Umm, `01`, `02` instead of `1`, `2`? Quick and dirty workaround.
