### ISSUE TITLE
nemo-sendto

### ISSUE THREAD

**Issue by brmmm3** [linuxmint/nemo-extensions#184]
I'm wondering where is the sendto extension? In the README this extensions is mentioned as working.
Best Regards,
Martin

**Comment by psyray** [comment]
Hi,

Yes where it is ?

**Comment by mtwebster** [comment]
It is just a nemo action now (check in /usr/share/nemo/actions)

You can modify/customize it by copying that into ~/.local/share/nemo/actions - for more info, in nemo click Edit->Plugins, then click the folder button in the Actions view.

**Comment by psyray** [comment]
:+1: 

For those who want, like me, to send files by bluetooth save the code below to 
`~/.local/share/nemo/actions/Send_by_bluetooth.nemo_action`
(Sending files with double quote in filename not working)
```
[Nemo Action]
Active=true
Name[en_GB]=Send by Bluetooth
Name[fr]=Envoyer par Bluetooth
Comment[en_GB]=Send one or several files by Bluetooth
Comment[fr]=Envoyer un ou plusieurs fichiers par Bluetooth
Exec=blueman-sendto %F
Icon-Name=bluetooth
Selection=Any
Extensions=any
Dependencies=blueman-sendto;
Quote=double
```

**Comment by psyray** [comment]
Attach files to Thunderbird
```
[Nemo Action]
Active=true
Name[en_GB]=Send with Thunderbird
Name[fr]=Envoyer avec Thunderbird
Comment[en_GB]=Attach one or several files to Thunderbird message
Comment[fr]=Attacher un ou plusieurs fichiers à un message Thunderbird
Exec=thunderbird -compose to=,"attachment='%F'"
Icon-Name=thunderbird
Selection=Any
Extensions=any
Separator=,
Dependencies=thunderbird;
```
