### ISSUE TITLE
dropbox deamon hangs at 100% during first run

### ISSUE THREAD

**Issue by infektedpc** [linuxmint/nemo-extensions#20]
just did a clean install of linux mint 14 cinnamon and installed nemo-dropbox hung at 100%

sudo dpkg -r nemo-dropbox
cd ~ && wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64" | tar xzf -
sudo apt-get install nemo-dropbox

seems to fix the problem

i believe the newer deamon just needs to be added to the package but i dont really know how this stuff works

**Comment by monsta** [comment]
Does it still happen in Mint 17.x?

**Comment by semdoc** [comment]
Works for me on Linux Mint 17.2. Thanx :)
