### ISSUE TITLE
[Nemo-terminal] Nemo does not follow terminal

### ISSUE THREAD

**Issue by m4l3z** [linuxmint/nemo-extensions#201]
Hi, 

I tried setting the dconf of nemo-terminal to nemo follows terminal and nemo and terminal synchronized. 
But nemo never follows the terminal, is it a bug is it not implemented yet ? 
Linux mint 18, Nemo 3.0.6.

**Comment by m4l3z** [comment]
Damn.. I can't read. The feature is still in development. Sorry

**Comment by leigh123linux** [comment]
https://github.com/linuxmint/nemo-extensions/issues/134

**Comment by yuuhikaze** [comment]
Hi!
any updates on this?
it would be super useful for changing directories fast with zoxide (`zi`)

**Comment by yuuhikaze** [comment]
> it would be super useful for changing directories fast with zoxide (`zi`)
This simple script does it:

```bash
#!/bin/bash

set -uo pipefail
IFS=$'\n'

selected_dir="$(zoxide query -i)"
[ -z "$selected_dir" ] && exit
nemo --existing-window "$selected_dir"
```
