### ISSUE TITLE
[nemo-share] Sharing encrypted folders to other Samba users does not work

### ISSUE THREAD

**Issue by blendenzo** [linuxmint/nemo-extensions#202]
When using an encrypted home folder, the "Sharing Options" do not properly allow other Samba users to view and/or edit files in the shared folder.  To allow sharing encrypted folders to function, nemo-share would need to add the "force user" setting in the Samba configuration for the shared folder.

For example, Tom wants to share /home/tom/Public (which is located in his encrypted home folder) on the network with other registered Samba users, but does not want to allow guest access. He adds Sally to the Samba server, then uses nemo-share to share his folder on the network and allow other users write access, (but he does not allow guest access).  When Sally tries to connect to the shared folder using her Samba credentials, she receives a "Permission denied" error.  This apparently happens because Sally's user on the Samba server does not have the ability to use Tom's file encryption key.  If "force user = tom" is used, Samba will perform file operations as tom, allowing Sally (and other valid users) to access the files as expected.

**Comment by clefebvre** [comment]
Tracked at https://github.com/linuxmint/linuxmint/issues/125.

**Comment by clefebvre** [comment]
I didn't really want to mess with smb.conf for a niche case and a usershare, especially with an option like this. It's important to raise the user's awareness as to why this could fail though and lead him/her in the right direction. I did that with https://github.com/linuxmint/nemo-extensions/commit/ded12a6e456f15f236c612342849810879ea746a.
