### ISSUE TITLE
[nemo-preview] How to make it work on Arch Linux?

### ISSUE THREAD

**Issue by nick-s-b** [linuxmint/nemo-extensions#203]
Hi all,

I'm using Cinnamon under Arch and I'm more than happy with how it works except for one issue: I can't get nemo-preview to work. Pretty much everything else works fine.

I've installed the `community/nemo-preview 3.0.0-1` package but when I select an image and press the space bar inside of nemo, nothing happens.

Has anyone been able to get it working? What is the secret? I've been looking and trying various things but haven't been able to get it working.

Thanks!

**Comment by leigh123linux** [comment]
nemo-preview works fine in fedora including F26 (rawhide).
To activate, left click on file to be previewed then use 'space bar' to view.

**Comment by nick-s-b** [comment]
@leigh123linux yeah, I know how it is suppose to work (I've used Linux Mint for over 6 months) but it doesn't do anything in my install.  I've looked at glass.log but there's nothing there. I'm suspecting there might be a way to ask nemo to log more but I don't know how. I've also looked at Looking Glass window while cinnamon and nemo are running and don't see anything there. 

Do you know of any ways to debug it? I'm at loss as where to start... 

Thanks for reading and replying!

**Comment by mtwebster** [comment]
Try starting `nemo-preview` from a terminal.  It's a dbus service that is normally called on-demand by nemo, but you can start it pre-emptively, and see what, if any, errors it generates.

Make sure it's not already running for some reason (kill it if necessary)

**Comment by mtwebster** [comment]
What gtk theme are you using?  Try Adwaita.

**Comment by nick-s-b** [comment]
@mtwebster I was using Arc. I've set my themes to this now:

![https://i.imgur.com/i5pJQ2Kl.jpg](https://i.imgur.com/i5pJQ2Kl.jpg)

This is the `nemo-preview` output:

```
<all the MIME stuff before>
Cjs-Message: JS WARNING: [/usr/share/nemo-preview/js/ui/mainWindow.js 33]: assignment to undeclared variable screen
Cjs-Message: JS WARNING: [/usr/share/nemo-preview/js/ui/mainWindow.js 34]: assignment to undeclared variable mon
Cjs-Message: JS WARNING: [/usr/share/nemo-preview/js/ui/mainWindow.js 35]: assignment to undeclared variable s

(nemo-preview-start:6914): Gtk-WARNING **: Theme parsing error: gtk-style.css:12:22: Using Pango syntax for the font: style property is deprecated; please use CSS syntax

(nemo-preview-start:6914): Gtk-WARNING **: Theme parsing error: gtk-style.css:24:26: The :prelight pseudo-class is deprecated. Use :hover instead.

(nemo-preview-start:6914): Gtk-WARNING **: Theme parsing error: gtk-style.css:25:26: The :prelight pseudo-class is deprecated. Use :hover instead.

(nemo-preview-start:6914): Gtk-WARNING **: Theme parsing error: gtk-style.css:29:26: The :prelight pseudo-class is deprecated. Use :hover instead.

(nemo-preview-start:6914): Gtk-WARNING **: Theme parsing error: gtk-style.css:30:26: The :prelight pseudo-class is deprecated. Use :hover instead.

(nemo-preview-start:6914): Gtk-WARNING **: Theme parsing error: gtk-style.css:48:33: The style property GtkWidget:focus-line-width is deprecated and shouldn't be used anymore. It will be removed in a future version

(nemo-preview-start:6914): Cjs-WARNING **: JS ERROR: Gtk.CssProviderError: gtk-style.css:12:10not a number
Application<._defineStyleAndThemes@/usr/share/nemo-preview/js/ui/application.js:84
wrapper@resource:///org/gnome/gjs/modules/lang.js:169
Application<.vfunc_startup@/usr/share/nemo-preview/js/ui/application.js:70
wrapper@resource:///org/gnome/gjs/modules/lang.js:169
run@/usr/share/nemo-preview/js/ui/main.js:55
@main.c:2

```

**Comment by mtwebster** [comment]
Open `/usr/share/nemo-preview/style/gtk-style.css`  (as root)

On line 12, add `px` after the 10 - it should read:

`font: 10px monospace;`

Save, then retry nemo-preview.

**Comment by nick-s-b** [comment]
OK, that section now looks like:

```
  8 GtkSourceView {
  9     color: @np_text_color;
 10     background-color: shade (@np_fg_color, 1.10);
 11     font: 10px Monospace;
 12     /* font: Monospace 10; */
 13 }
```

and the error is now this:

```
Cjs-Message: JS WARNING: [/usr/share/nemo-preview/js/ui/mainWindow.js 35]: assignment to undeclared variable s

(nemo-preview-start:7840): Gtk-WARNING **: Theme parsing error: gtk-style.css:25:26: The :prelight pseudo-class is deprecated. Use :hover instead.

(nemo-preview-start:7840): Gtk-WARNING **: Theme parsing error: gtk-style.css:26:26: The :prelight pseudo-class is deprecated. Use :hover instead.

(nemo-preview-start:7840): Gtk-WARNING **: Theme parsing error: gtk-style.css:30:26: The :prelight pseudo-class is deprecated. Use :hover instead.

(nemo-preview-start:7840): Gtk-WARNING **: Theme parsing error: gtk-style.css:31:26: The :prelight pseudo-class is deprecated. Use :hover instead.

(nemo-preview-start:7840): Gtk-WARNING **: Theme parsing error: gtk-style.css:49:33: The style property GtkWidget:focus-line-width is deprecated and shouldn't be used anymore. It will be removed in a future version

(nemo-preview-start:7840): Cjs-WARNING **: JS ERROR: Gtk.CssProviderError: gtk-style.css:36:14not a number
Application<._defineStyleAndThemes@/usr/share/nemo-preview/js/ui/application.js:84
wrapper@resource:///org/gnome/gjs/modules/lang.js:169
Application<.vfunc_startup@/usr/share/nemo-preview/js/ui/application.js:70
wrapper@resource:///org/gnome/gjs/modules/lang.js:169
run@/usr/share/nemo-preview/js/ui/main.js:55
@main.c:2

```

**Comment by mtwebster** [comment]
can you paste the entire contents of that file?  I want to be sure we're looking at the same version.

**Comment by nick-s-b** [comment]
Yep! Here is the whole file: /usr/share/nemo-preview/style/gtk-style.css

```
@define-color np_fg_color #ddddde;
@define-color np_bg_color #333;
@define-color np_text_color #2e3436;

GtkWindow {
    color: @np_fg_color;
}

GtkSourceView {
    color: @np_text_color;
    background-color: shade (@np_fg_color, 1.10);
    font: 10px monospace;
    /* font: Monospace 10; */
}

NemoPreviewFontWidget {
    background-color: transparent;
}

.scrollbar.slider,
.scrollbar.button {
    background-color: shade (@np_bg_color, 1.30);
}

.scrollbar.button:prelight,
.scrollbar.slider:prelight {
    background-color: shade (@np_bg_color, 1.45);
}

.scrollbar.button:prelight:active,
.scrollbar.slider:prelight:active {
    background-color: shade (@np_bg_color, 1.70);
}

.np-decoration {
    font: bold;
}

.np-decoration.button {
    background-image: none;
    padding: 4px;

    border-image: none;
    border-style: none;
    border-radius: 0;
    border-width: 0;
    background-color: alpha (#000, 0.0);

    -GtkWidget-focus-line-width: 0;
}

.np-decoration.button:hover {
    background-image: -gtk-gradient(linear,
                                    left top,
                                    left bottom,
                                    from(alpha(@np_bg_color, 0.0)),
                                    color-stop(0.50, alpha(@np_bg_color, 0.66)),
                                    to(alpha(@np_bg_color, 0.0)));
}

.np-decoration.button:hover:active {
    background-image: -gtk-gradient(linear,
                                    left top,
                                    left bottom,
                                    from(alpha(@np_bg_color, 0.0)),
                                    color-stop(0.50, @np_bg_color),
                                    to(alpha(@np_bg_color, 0.0)));
}
```

**Comment by mtwebster** [comment]
Ahh - you're only on version 3.0.x for nemo-preview - you lack this patch:

https://github.com/linuxmint/nemo-extensions/commit/4cc0c028cffcb281d70e5a8321be18bffe7abed1

change that one line to `font-weight` and it should be fine.  I'm going to patch the `px` in as well (it works without but generates a deprecated warning).

**Comment by nick-s-b** [comment]
YAY! It now comes up and shows an image. There's only one small bug. If I press the space bar, the preview window goes white and doesn't disappear. It does go away if I press the close window widget.

**Comment by mtwebster** [comment]
I'm pretty sure that was another recent fix - does it give any sort of error when this happens if you run from a terminal?  I can't remember precisely what the issue was.

**Comment by mtwebster** [comment]
Actually, 3.0.0 is behind on a huge number of commits.  You'd do better attempting to build yourself from source (from the folder in this github repo) and the existing arch pkgbuild file.

**Comment by nick-s-b** [comment]
Ok, I rebooted just to make sure. Yep, the image turns white after I press the space to dismiss it.

I'll do the update!! Thank you much @mtwebster !!

**Comment by Palbear** [comment]
Hi All,
I have the same error with the updated gtk-style.css that is mentioned above. Is there any other issue that i should take care of?
Here is my teminal log after running nemo-preview:

`>> nemo-preview 
Cjs-Message: JS WARNING: [/usr/share/nemo-preview/js/ui/mimeHandler.js 61]: assignment to undeclared variable idx
Cjs-Message: JS LOG: Register mimetype application/pdf
Cjs-Message: JS LOG: Register mimetype application/x-bzpdf
Cjs-Message: JS LOG: Register mimetype application/x-gzpdf
Cjs-Message: JS LOG: Register mimetype application/x-xzpdf
Cjs-Message: JS LOG: Register mimetype application/x-ext-pdf
Cjs-Message: JS LOG: Register mimetype application/postscript
Cjs-Message: JS LOG: Register mimetype application/x-bzpostscript
Cjs-Message: JS LOG: Register mimetype application/x-gzpostscript
Cjs-Message: JS LOG: Register mimetype image/x-eps
Cjs-Message: JS LOG: Register mimetype image/x-bzeps
Cjs-Message: JS LOG: Register mimetype image/x-gzeps
Cjs-Message: JS LOG: Register mimetype application/x-ext-ps
Cjs-Message: JS LOG: Register mimetype application/x-ext-eps
Cjs-Message: JS LOG: Register mimetype image/vnd.djvu
Cjs-Message: JS LOG: Register mimetype image/vnd.djvu+multipage
Cjs-Message: JS LOG: Register mimetype application/x-ext-djv
Cjs-Message: JS LOG: Register mimetype application/x-ext-djvu
Cjs-Message: JS LOG: Register mimetype image/tiff
Cjs-Message: JS LOG: Register mimetype application/x-dvi
Cjs-Message: JS LOG: Register mimetype application/x-bzdvi
Cjs-Message: JS LOG: Register mimetype application/x-gzdvi
Cjs-Message: JS LOG: Register mimetype application/x-ext-dvi
Cjs-Message: JS LOG: Register mimetype application/x-cbr
Cjs-Message: JS LOG: Register mimetype application/x-cbz
Cjs-Message: JS LOG: Register mimetype application/x-cb7
Cjs-Message: JS LOG: Register mimetype application/x-cbt
Cjs-Message: JS LOG: Register mimetype application/x-ext-cbr
Cjs-Message: JS LOG: Register mimetype application/x-ext-cbz
Cjs-Message: JS LOG: Register mimetype application/vnd.comicbook+zip
Cjs-Message: JS LOG: Register mimetype application/x-ext-cb7
Cjs-Message: JS LOG: Register mimetype application/x-ext-cbt
Cjs-Message: JS LOG: Register mimetype application/oxps
Cjs-Message: JS LOG: Register mimetype application/vnd.ms-xpsdocument
Cjs-Message: JS LOG: Register mimetype application/vnd.oasis.opendocument.text
Cjs-Message: JS LOG: Register mimetype application/vnd.oasis.opendocument.presentation
Cjs-Message: JS LOG: Register mimetype application/vnd.oasis.opendocument.spreadsheet
Cjs-Message: JS LOG: Register mimetype application/msword
Cjs-Message: JS LOG: Register mimetype application/vnd.ms-excel
Cjs-Message: JS LOG: Register mimetype application/vnd.ms-powerpoint
Cjs-Message: JS LOG: Register mimetype application/rtf
Cjs-Message: JS LOG: Register mimetype text/html
Cjs-Message: JS LOG: Register mimetype text/plain
Cjs-Message: JS LOG: Register mimetype image/png
Cjs-Message: JS LOG: Register mimetype image/bmp
Cjs-Message: JS LOG: Register mimetype image/x-bmp
Cjs-Message: JS LOG: Register mimetype image/x-MS-bmp
Cjs-Message: JS LOG: Register mimetype image/gif
Cjs-Message: JS LOG: Register mimetype image/x-icon
Cjs-Message: JS LOG: Register mimetype image/x-ico
Cjs-Message: JS LOG: Register mimetype image/x-win-bitmap
Cjs-Message: JS LOG: Register mimetype image/vnd.microsoft.icon
Cjs-Message: JS LOG: Register mimetype application/ico
Cjs-Message: JS LOG: Register mimetype image/ico
Cjs-Message: JS LOG: Register mimetype image/icon
Cjs-Message: JS LOG: Register mimetype text/ico
Cjs-Message: JS LOG: Register mimetype application/x-navi-animation
Cjs-Message: JS LOG: Register mimetype image/jpeg
Cjs-Message: JS LOG: Register mimetype image/x-portable-anymap
Cjs-Message: JS LOG: Register mimetype image/x-portable-bitmap
Cjs-Message: JS LOG: Register mimetype image/x-portable-graymap
Cjs-Message: JS LOG: Register mimetype image/x-portable-pixmap
Cjs-Message: JS LOG: Register mimetype image/tiff
Cjs-Message: JS LOG: Register mimetype image/x-xpixmap
Cjs-Message: JS LOG: Register mimetype image/x-xbitmap
Cjs-Message: JS LOG: Register mimetype image/x-tga
Cjs-Message: JS LOG: Register mimetype image/x-icns
Cjs-Message: JS LOG: Register mimetype image/jp2
Cjs-Message: JS LOG: Register mimetype image/jpeg2000
Cjs-Message: JS LOG: Register mimetype image/jpx
Cjs-Message: JS LOG: Register mimetype image/x-quicktime
Cjs-Message: JS LOG: Register mimetype image/qtif
Cjs-Message: JS LOG: Register mimetype image/svg+xml
Cjs-Message: JS LOG: Register mimetype image/svg
Cjs-Message: JS LOG: Register mimetype image/svg-xml
Cjs-Message: JS LOG: Register mimetype image/vnd.adobe.svg+xml
Cjs-Message: JS LOG: Register mimetype text/xml-svg
Cjs-Message: JS LOG: Register mimetype image/svg+xml-compressed
Cjs-Message: JS LOG: Register mimetype audio/3gpp
Cjs-Message: JS LOG: Register mimetype audio/ac3
Cjs-Message: JS LOG: Register mimetype audio/AMR
Cjs-Message: JS LOG: Register mimetype audio/AMR-WB
Cjs-Message: JS LOG: Register mimetype audio/basic
Cjs-Message: JS LOG: Register mimetype audio/flac
Cjs-Message: JS LOG: Register mimetype audio/midi
Cjs-Message: JS LOG: Register mimetype audio/mp2
Cjs-Message: JS LOG: Register mimetype audio/mp4
Cjs-Message: JS LOG: Register mimetype audio/mpeg
Cjs-Message: JS LOG: Register mimetype audio/ogg
Cjs-Message: JS LOG: Register mimetype audio/prs.sid
Cjs-Message: JS LOG: Register mimetype audio/vnd.rn-realaudio
Cjs-Message: JS LOG: Register mimetype audio/x-aiff
Cjs-Message: JS LOG: Register mimetype audio/x-ape
Cjs-Message: JS LOG: Register mimetype audio/x-flac
Cjs-Message: JS LOG: Register mimetype audio/x-gsm
Cjs-Message: JS LOG: Register mimetype audio/x-it
Cjs-Message: JS LOG: Register mimetype audio/x-m4a
Cjs-Message: JS LOG: Register mimetype audio/x-matroska
Cjs-Message: JS LOG: Register mimetype audio/x-mod
Cjs-Message: JS LOG: Register mimetype audio/x-mp3
Cjs-Message: JS LOG: Register mimetype audio/x-mpeg
Cjs-Message: JS LOG: Register mimetype audio/x-ms-asf
Cjs-Message: JS LOG: Register mimetype audio/x-ms-asx
Cjs-Message: JS LOG: Register mimetype audio/x-ms-wax
Cjs-Message: JS LOG: Register mimetype audio/x-ms-wma
Cjs-Message: JS LOG: Register mimetype audio/x-musepack
Cjs-Message: JS LOG: Register mimetype audio/x-pn-aiff
Cjs-Message: JS LOG: Register mimetype audio/x-pn-au
Cjs-Message: JS LOG: Register mimetype audio/x-pn-wav
Cjs-Message: JS LOG: Register mimetype audio/x-pn-windows-acm
Cjs-Message: JS LOG: Register mimetype audio/x-realaudio
Cjs-Message: JS LOG: Register mimetype audio/x-real-audio
Cjs-Message: JS LOG: Register mimetype audio/x-s3m
Cjs-Message: JS LOG: Register mimetype audio/x-sbc
Cjs-Message: JS LOG: Register mimetype audio/x-speex
Cjs-Message: JS LOG: Register mimetype audio/x-stm
Cjs-Message: JS LOG: Register mimetype audio/x-tta
Cjs-Message: JS LOG: Register mimetype audio/x-wav
Cjs-Message: JS LOG: Register mimetype audio/x-wavpack
Cjs-Message: JS LOG: Register mimetype audio/x-vorbis
Cjs-Message: JS LOG: Register mimetype audio/x-vorbis+ogg
Cjs-Message: JS LOG: Register mimetype audio/x-xm
Cjs-Message: JS LOG: Register mimetype application/x-flac
Cjs-Message: JS LOG: Register mimetype application/mxf
Cjs-Message: JS LOG: Register mimetype application/ogg
Cjs-Message: JS LOG: Register mimetype application/ram
Cjs-Message: JS LOG: Register mimetype application/sdp
Cjs-Message: JS LOG: Register mimetype application/vnd.apple.mpegurl
Cjs-Message: JS LOG: Register mimetype application/vnd.ms-wpl
Cjs-Message: JS LOG: Register mimetype application/vnd.rn-realmedia
Cjs-Message: JS LOG: Register mimetype application/x-extension-m4a
Cjs-Message: JS LOG: Register mimetype application/x-extension-mp4
Cjs-Message: JS LOG: Register mimetype application/x-flash-video
Cjs-Message: JS LOG: Register mimetype application/x-matroska
Cjs-Message: JS LOG: Register mimetype application/x-netshow-channel
Cjs-Message: JS LOG: Register mimetype application/x-ogg
Cjs-Message: JS LOG: Register mimetype application/x-quicktimeplayer
Cjs-Message: JS LOG: Register mimetype application/x-shorten
Cjs-Message: JS LOG: Register mimetype image/vnd.rn-realpix
Cjs-Message: JS LOG: Register mimetype image/x-pict
Cjs-Message: JS LOG: Register mimetype misc/ultravox
Cjs-Message: JS LOG: Register mimetype text/x-google-video-pointer
Cjs-Message: JS LOG: Register mimetype video/3gp
Cjs-Message: JS LOG: Register mimetype video/3gpp
Cjs-Message: JS LOG: Register mimetype video/dv
Cjs-Message: JS LOG: Register mimetype video/divx
Cjs-Message: JS LOG: Register mimetype video/fli
Cjs-Message: JS LOG: Register mimetype video/flv
Cjs-Message: JS LOG: Register mimetype video/mp2t
Cjs-Message: JS LOG: Register mimetype video/mp4
Cjs-Message: JS LOG: Register mimetype video/mp4v-es
Cjs-Message: JS LOG: Register mimetype video/mpeg
Cjs-Message: JS LOG: Register mimetype video/msvideo
Cjs-Message: JS LOG: Register mimetype video/ogg
Cjs-Message: JS LOG: Register mimetype video/quicktime
Cjs-Message: JS LOG: Register mimetype video/vivo
Cjs-Message: JS LOG: Register mimetype video/vnd.divx
Cjs-Message: JS LOG: Register mimetype video/vnd.mpegurl
Cjs-Message: JS LOG: Register mimetype video/vnd.rn-realvideo
Cjs-Message: JS LOG: Register mimetype video/vnd.vivo
Cjs-Message: JS LOG: Register mimetype video/webm
Cjs-Message: JS LOG: Register mimetype video/x-anim
Cjs-Message: JS LOG: Register mimetype video/x-avi
Cjs-Message: JS LOG: Register mimetype video/x-flc
Cjs-Message: JS LOG: Register mimetype video/x-fli
Cjs-Message: JS LOG: Register mimetype video/x-flic
Cjs-Message: JS LOG: Register mimetype video/x-flv
Cjs-Message: JS LOG: Register mimetype video/x-m4v
Cjs-Message: JS LOG: Register mimetype video/x-matroska
Cjs-Message: JS LOG: Register mimetype video/x-mpeg
Cjs-Message: JS LOG: Register mimetype video/x-mpeg2
Cjs-Message: JS LOG: Register mimetype video/x-ms-asf
Cjs-Message: JS LOG: Register mimetype video/x-ms-asx
Cjs-Message: JS LOG: Register mimetype video/x-msvideo
Cjs-Message: JS LOG: Register mimetype video/x-ms-wm
Cjs-Message: JS LOG: Register mimetype video/x-ms-wmv
Cjs-Message: JS LOG: Register mimetype video/x-ms-wmx
Cjs-Message: JS LOG: Register mimetype video/x-ms-wvx
Cjs-Message: JS LOG: Register mimetype video/x-nsv
Cjs-Message: JS LOG: Register mimetype video/x-ogm+ogg
Cjs-Message: JS LOG: Register mimetype video/x-theora+ogg
Cjs-Message: JS LOG: Register mimetype video/x-totem-stream
Cjs-Message: JS LOG: Register mimetype audio/x-pn-realaudio
Cjs-Message: JS LOG: Register mimetype application/x-font-ttf
Cjs-Message: JS LOG: Register mimetype application/x-font-otf
Cjs-Message: JS LOG: Register mimetype application/x-font-pcf
Cjs-Message: JS LOG: Register mimetype application/x-font-type1
Cjs-Message: JS WARNING: [/usr/share/nemo-preview/js/ui/mainWindow.js 33]: assignment to undeclared variable screen
Cjs-Message: JS WARNING: [/usr/share/nemo-preview/js/ui/mainWindow.js 34]: assignment to undeclared variable mon
Cjs-Message: JS WARNING: [/usr/share/nemo-preview/js/ui/mainWindow.js 35]: assignment to undeclared variable s

(nemo-preview-start:23301): Gtk-WARNING **: Theme parsing error: gtk-style.css:12:12: Not using units is deprecated. Assuming 'px'.

(nemo-preview-start:23301): Gtk-WARNING **: Theme parsing error: gtk-style.css:24:26: The :prelight pseudo-class is deprecated. Use :hover instead.

(nemo-preview-start:23301): Gtk-WARNING **: Theme parsing error: gtk-style.css:25:26: The :prelight pseudo-class is deprecated. Use :hover instead.

(nemo-preview-start:23301): Gtk-WARNING **: Theme parsing error: gtk-style.css:29:26: The :prelight pseudo-class is deprecated. Use :hover instead.

(nemo-preview-start:23301): Gtk-WARNING **: Theme parsing error: gtk-style.css:30:26: The :prelight pseudo-class is deprecated. Use :hover instead.

(nemo-preview-start:23301): Gtk-WARNING **: Theme parsing error: gtk-style.css:48:33: The style property GtkWidget:focus-line-width is deprecated and shouldn't be used anymore. It will be removed in a future version
/usr/bin/nemo-preview: line 15: 23301 Segmentation fault      (core dumped) /usr/lib/nemo-preview/nemo-preview-start
`

**Comment by leigh123linux** [comment]
If you can reproduce the issue using the latest git feel free to reopen.
