### ISSUE TITLE
Compressing compressed files

### ISSUE THREAD

**Issue by nazar-pc** [linuxmint/nemo-extensions#204]
I have *.zip file with Android ROM and I want to compress it with 7z, but context menu doesn't contain option for compression, it allows to mount archive or decompress it instead.

Could you stop hiding compression options regardless of file type?

Nemo 3.2.2, nemo-fileroller 3.2.0

**Comment by EduardDopler** [comment]
This is rather opinion-based. IMHO this is not what the typical user wants. He/She wants to compress uncompressed files and uncompress compress files. Space in the context menu is scarce and the system, extensions and plugins contend with eachother for it. Besides, from a technical point of view, compressing one or more ZIP files with 7z more often than not produce larger, worse compressed results. Try it yourself: Compress the ZIP files with 7z and compare it to compressing the content of the ZIP files with 7z.
Anyway, I wouldn't change that. If you need that, open fileroller by hand.
