### ISSUE TITLE
seahorse-tool will not encrypt.

### ISSUE THREAD

**Issue by unl1k3ly** [linuxmint/nemo-extensions#205]
Hi, I'm running Mint18 and seahorse-tool will not encrypt files. Decryption works just fine.

I tried it from Mint repo and compiling and it will just not work.

Even manually, " ./seahorse-tool -e test.txt" no error output are shown. 

Would you please, check ??

Thanks

**Comment by gneb962** [comment]
It's a very old issue, see [#42](https://github.com/linuxmint/nemo-extensions/issues/42)

**Comment by Zache51** [comment]
If I would try to find the bug and fix it, is "nemo-seahorse.c" the only file I have to look into? I am not affiliated with Linux Mint in any way but is it ok to help with this?

**Comment by meckli** [comment]
Well, I also have that Problem on LinuxMint 18.1 Cinnamon,  trying to encrypt files or folders with the right-click-menu in nemo. I get a selection menu popup for the key-selection but after pressing O.K. it just disappaers and nothing else matters.  

btw. Signing though works just fine.
