### ISSUE TITLE
evince dependency of nemo-preview

### ISSUE THREAD

**Issue by oberon2007** [linuxmint/nemo-extensions#207]
With the availability of **xreader** it seems weird to have to install **evince** alongside it as a dependency of **nemo-preview**. Is there a way, this dependency could be dropped?

**Comment by GLolol** [comment]
As far as I can tell nemo-preview actually uses evince libraries for PDF handling, so it's not as simple as just removing the dependency: https://github.com/linuxmint/nemo-extensions/blob/master/nemo-preview/src/libnemo-preview/nemo-preview-pdf-loader.c#L31-L32
