### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by v1nce** [linuxmint/nemo-extensions#220]
Here are my translation for french
Sorry I'm not familiar with po file editing so I provided only the strings that needed translation
I hope it wil be usefull anyway

#: ../src/nemo-compare.py:115 ../src/nemo-compare.py:138
msgid "Compare to: "
msgstr "Comparer avec : "

#: ../src/nemo-compare.py:116
msgid "Compare to the file remembered before"
msgstr "Comparer avec le fichier précédemment sélectionné"

#: ../src/nemo-compare.py:125
msgid "Compare Later"
msgstr "Comparer ultérieurement"

#: ../src/nemo-compare.py:126
msgid "Remember file for later comparison"
msgstr "Enregistrer le fichier pour une comparaison ultérieure"

#: ../src/nemo-compare.py:139
msgid "Compare selected files to the file remembered before"
msgstr "Comparer les fichiers avec le fichier précédemment enregistré"

#: ../src/nemo-compare.py:150
msgid "Compare"
msgstr "Comparer"

#: ../src/nemo-compare.py:151
msgid "Compare selected files"
msgstr "Comparer les fichiers sélectionnés"

#: ../src/nemo-compare-preferences.py:95
msgid "Nemo Compare Extension Preferences"
msgstr "Paramétrages de l'extension de comparaison"

#. normal diff
#: ../src/nemo-compare-preferences.py:103
msgid "Normal Diff"
msgstr "Diff classique"

#. 3-way diff
#: ../src/nemo-compare-preferences.py:115
msgid "Three-Way Diff"
msgstr "Diff ternaire"

#. n-way diff
#: ../src/nemo-compare-preferences.py:127
msgid "N-Way Diff"
msgstr "Diff N-aire"

**Comment by NikoKrause** [comment]
You can use the application `poedit`. Install this application and open the `nemo-compare.pot` file with this application. In the application itself you can create a new translation, select French. And if you finished the translation, save the file and create a pull request here, by adding the `fr.po`, which you have created with poedit.

**Comment by NikoKrause** [comment]
The translation of nemo-extensions is now handled on launchpad too.
So this issue can be closed.

@JosephMcc
