### ISSUE TITLE
Nemo preview in Mint 18.2

### ISSUE THREAD

**Issue by Cos-mo** [linuxmint/nemo-extensions#222]
Mint 18.2 beta Cinnamon 3.4.1 64 bit:

Nemo preview does not respond, if I press the space bar, although synaptic says, it is installed.

Tested with the unaltered file .bashrc in user's home.

**Comment by leigh123linux** [comment]
Post the output for this command and press the space bar.
```
nemo-preview
```

**Comment by Cos-mo** [comment]
`$ nemo-preview
OpenGL Warning: crPixelCopy3D:  simply crMemcpy'ing from srcPtr to dstPtr

(nemo-preview-start:2127): Cjs-WARNING **: JS ERROR: Error: Requiring WebKit2, version none: Typelib file for namespace 'WebKit2' (any version) not found
@/usr/share/nemo-preview/js/viewers/html.js:31:7

Segmentation fault
`
To add: This is a fresh new install, nothing added, removed ar altered.

Environment: VirtualBox
