### ISSUE TITLE
[nemo-fileroller] Translation

### ISSUE THREAD

**Issue by Gena95** [linuxmint/nemo-extensions#229]
Can I translate this extesion? I don't found 'po' folder in sources. Do I need to create .pot file manually?

**Comment by NikoKrause** [comment]
Can you show a screenshot, where it is not translated?

**Comment by Gena95** [comment]
@NikoKrause of course! I selected untranslated lines by a red line:
<a target="_blank" href="https://itmages.ru/image/view/5964393/c70b3273"><img src="http://storage9.static.itmages.ru/i/17/0727/s_1501187968_9580869_c70b32739a.png" /></a>
<a target="_blank" href="https://itmages.ru/image/view/5964392/59b763e1"><img src="http://storage9.static.itmages.ru/i/17/0727/s_1501187968_5442197_59b763e1a8.png" /></a>
This extension ([nemo-fileroller](https://github.com/linuxmint/nemo-extensions/tree/master/nemo-fileroller) I think) don't contain 'po'  folder.

**Comment by NikoKrause** [comment]
Hmm... You use Russian. I can find those strings only here https://github.com/linuxmint/gnome-apps/blob/master/file-roller/po/ru.po

But that's for nautilus-fileroller and they are translated there. Though nemo is a fork of nautilus, and those strings haven't changed for years, so I wonder what happens here.

Do you use Linux Mint 18.2 Cinnamon? Do you have `file-roller` AND `nemo-fileroller`installed?

**Comment by NikoKrause** [comment]
Ok I have been able to reproduce your issue and I know what's going on now.
It's a pretty simple solution. You haven't installed all translation files.

Please go to Languages (`Меню - Параметры - Языки`)
There you press the bottom at the top to install language packages (`Установка и удаление языков...`)
![screenshot-window-2017-07-28-084159](https://user-images.githubusercontent.com/8415124/28705934-46be383a-7372-11e7-9c8d-e974a74d1ec9.png)
You have to install all `Russian, Russia UTF-8` packages (`Установить языковые пакеты`)

When all packages are installed, press the button to apply your selected language system wide (`Применить для вцей системы`)

Now log out or restart computer and nemo-fileroller should be translated properly to Russian.

I hope this solves your problem. Please let me know.

**Comment by Gena95** [comment]
@NikoKrause I use Arch Linux and I haven't language-tool :(
My nemo-fileroller and file-roller installed from official repository. Maybe this problem of my distro?

**Comment by NikoKrause** [comment]
What's the output of `locale` in your terminal?

**Comment by Gena95** [comment]
@NikoKrause 
locale
LANG=ru_RU.utf8
LC_CTYPE="ru_RU.utf8"
LC_NUMERIC=ru_RU.UTF-8
LC_TIME=ru_RU.UTF-8
LC_COLLATE="ru_RU.utf8"
LC_MONETARY=ru_RU.UTF-8
LC_MESSAGES="ru_RU.utf8"
LC_PAPER=ru_RU.UTF-8
LC_NAME=ru_RU.UTF-8
LC_ADDRESS=ru_RU.UTF-8
LC_TELEPHONE=ru_RU.UTF-8
LC_MEASUREMENT=ru_RU.UTF-8
LC_IDENTIFICATION=ru_RU.UTF-8
LC_ALL=

**Comment by NikoKrause** [comment]
I never used arch, you need to check, if all translation packs are installed.
Maybe checking the `gnome-control-center`
It's a missing package, you need to find out which one

**Comment by Gena95** [comment]
In Arch Linux file-roller have translation in package.
[This package](https://www.archlinux.org/packages/extra/x86_64/file-roller/files/) have file usr/share/locale/ru/LC_MESSAGES/file-roller.mo and interface of file-roller translated into russian. But context menus, which are on my screenshots, untranslated.

**Comment by NikoKrause** [comment]
@theraser I see you run arch, maybe you can help here?

**Comment by NikoKrause** [comment]
Ok I found the translation package.
What's the output of `locate roller.mo`

**Comment by Gena95** [comment]
This command don't installed in my distro. But file exists here /usr/share/locale/ru/LC_MESSAGES/file-roller.mo

**Comment by NikoKrause** [comment]
I have it installed here:
```
/usr/share/locale-langpack/ru/LC_MESSAGES/file-roller.mo
```

**Comment by Gena95** [comment]
Do I need to try move this file?

**Comment by NikoKrause** [comment]
You can try to copy it to this directory

**Comment by NikoKrause** [comment]
You need to log out and log back in or to restart the computer after copying the file

**Comment by Gena95** [comment]
Hmm... I think this is specific distro folder. I haven't folder `locale-langpack,` only `locale` folder exists:(
Maybe file-roller form official distro come from gnome sources?

**Comment by NikoKrause** [comment]
Use should ask some Arch users.

**Comment by theraser** [comment]
After installing `nemo-fileroller` using Arch Linux you may find something at
`/usr/share/locale/ru/LC_MESSAGES/file-roller.mo`

You can use `find /usr -name file-roller.mo` as an (slow) alternative to `locate` for finding all those files. If there is something more I can help you with please let me know.

**Comment by Gena95** [comment]
@theraser, yes, file located here:
```
file /usr/share/locale/ru/LC_MESSAGES/file-roller.mo
/usr/share/locale/ru/LC_MESSAGES/file-roller.mo: GNU message catalog (little endian), revision 0.0, 270 messages
```

**Comment by NikoKrause** [comment]
Create a .mo file from this .po file and replace your file-roller.mo https://github.com/linuxmint/gnome-apps/blob/master/file-roller/po/ru.po

**Comment by NikoKrause** [comment]
Can you upload your .mo file here?

**Comment by Gena95** [comment]
@NikoKrause Of course!
[Here](https://drive.google.com/open?id=0B-kRBDJhZZnzZVI5QVVRbUlieG8) is my file.

How to convert .po from [here](https://github.com/linuxmint/gnome-apps/blob/master/file-roller/po/ru.po) to .mo?

**Comment by NikoKrause** [comment]
I converted you .mo file to .po and as expected it doesn't contain the strings from your screenshot.

I don't know, which commands arch has or has not. So google or try an online converter:
https://ezgif.com/po-to-mo

**Comment by Gena95** [comment]
Okay, thank you! I convert fully translated .po file to .mo.
But why did in Arch this file not completelly translated?

**Comment by NikoKrause** [comment]
I assume you'll need to get in touch with the arch packager.
According to the link you mentioned above https://www.archlinux.org/packages/extra/x86_64/file-roller/
the last packager was Jan Steffens <jan.steffens@gmail.com>

There's nothing the Mint team can do about it.

**Comment by Gena95** [comment]
Thank you so much! I'll write to him.

**Comment by NikoKrause** [comment]
Related problem https://github.com/linuxmint/Cinnamon/issues/6352#issuecomment-319015071

**Comment by Gena95** [comment]
@NikoKrause yes, replacing .mo files helps. Strings from screenshoot became translated.
But new untranslated strings appear in file-roller:(
Maybe it's becouse in Arch repo new verion of file-roller?

**Comment by schlegel11** [comment]
I have the exact same problem only with german translation. Using an arch -> antergos system.
Do we have any news about that issue?
