### ISSUE TITLE
nemo-preview depends on gir1.2-clutter-gst-2.0 which is not available anymore for Debian Stretch

### ISSUE THREAD

**Issue by jean-christophe-manciot** [linuxmint/nemo-extensions#232]
Debian Stretch 9
nemo-preview 3.4.0

```
# dpkg -i nemo-preview_3.4.0_amd64.deb 
Selecting previously unselected package nemo-preview.
(Reading database ... 372967 files and directories currently installed.)
Preparing to unpack nemo-preview_3.4.0_amd64.deb ...
Unpacking nemo-preview (3.4.0) ...
dpkg: dependency problems prevent configuration of nemo-preview:
 nemo-preview depends on gir1.2-clutter-gst-2.0; however:
  Package gir1.2-clutter-gst-2.0 is not installed.

# apt install gir1.2-clutter-gst-2.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package gir1.2-clutter-gst-2.0
E: Couldn't find any package by glob 'gir1.2-clutter-gst-2.0'
E: Couldn't find any package by regex 'gir1.2-clutter-gst-2.0'
```

**Comment by leigh123linux** [comment]
You need to report your issue to debian bug tracker

**Comment by leigh123linux** [comment]
@fantu

Debian can remove it from there control file

https://github.com/linuxmint/nemo-extensions/pull/233

**Comment by jean-christophe-manciot** [comment]
@leigh123linux 
So, if I understand correctly, debian is responsible for maintaining the **debian folder within your own repository**? 
Unfortunately, debian bug tracker does not track bugs outside of their domain debian.org.
Furthermore, if this dependency is stated in debian/control, this means that it is used or was used at the time: are you sure it is not used anymore?

**Comment by leigh123linux** [comment]
@jean-christophe-manciot 

Where did you get the package?, I don't see it listed

https://anonscm.debian.org/git/pkg-cinnamon/

If it wasn't LMDE it isn't our problem to fix

**Comment by GLolol** [comment]
nemo-preview doesn't exist in Debian, so it's actually https://github.com/linuxmint/nemo-extensions/blob/master/nemo-preview/debian/control#L27-L31 which needs tweaking.

**Comment by jean-christophe-manciot** [comment]
@leigh123linux: @GLolol is right: it is so obvious that it did not need to be specified in the first place.
It seems that you are not aware that **there is a debian folder in all nemo extensions sources in this repository, in https://github.com/linuxmint/nemo-extensions**.

**Comment by leigh123linux** [comment]
@jean-christophe-manciot  You miss my point, why the hell should mint maintain compatibility with debian?
If you want to use mint's packaging you will need to adapt it to suit

FTR I removed the unused dep

https://github.com/linuxmint/nemo-extensions/commit/abc184dcf4a4234d01674079bb630d6981844956

**Comment by jean-christophe-manciot** [comment]
@leigh123linux Let's keep this conversation courteous. 
Maintaining debian folders allow people to build the latest nemo and its extensions on debian and all its descendants, such as Ubuntu....
Isn't it great to have one's own software be spread out on many Linux distributions?

**Comment by leigh123linux** [comment]
@jean-christophe-manciot  Mint tracks Ubuntu LTS so their packaging is old to suit them.
Trying to use their packaging on newer releases will require the user to modify it to suit, I wouldn't expect my rpm spec file to be compatible with any other rpm distro.

**Comment by clefebvre** [comment]
Hi,

You're both right to some extent.

The debian/ dir is Mint's packaging. Debian's packaging might or might not differ and is hosted by Debian and maintained directly.

That said, as much as possible and if it doesn't cause issues we can make our packaging work for Debian and other derivatives.

**Comment by jean-christophe-manciot** [comment]
Thanks for joining in @clefebvre. That's good news, especially because debian maintains only nemo, nemo-fileroller & nemo-python. The support for all other extensions has been dropped ~ 3 years ago. (https://anonscm.debian.org/git/pkg-cinnamon/nemo-extensions.git/)
