### ISSUE TITLE
[Feature Request] One repository for each nemo extension

### ISSUE THREAD

**Issue by jean-christophe-manciot** [linuxmint/nemo-extensions#239]
I have noticed that the latest version in debian changelogs of various nemo extensions  are diverging from the main nemo-extensions git tag (3.4.0).
For instance:
- nemo-emblems: 3.4.1
- nemo-preview: 3.4.2
- nemo-seahorse: 3.4.1
- nemo-share: 3.4.2

Transforming the nemo-extensions global epo into several repositories, one per extension, would allow you to independently **tag** each one at its current state.
We would have, for example:
- https://github.com/linuxmint/nemo-emblems
- https://github.com/linuxmint/nemo-preview
- https://github.com/linuxmint/nemo-seahorse
- https://github.com/linuxmint/nemo-share
... and so on

This new framework would allow us to trigger builds based on new tag(s), for each nemo extension.
Right now, we have no practical (automatic) way to know that there is a new extension tag.

**Comment by jean-christophe-manciot** [comment]
Hello @clefebvre,
Tagging the nemo-extensions repo with ```<nemo-extension>-<version>``` seems like a nice compromise.

**Comment by clefebvre** [comment]
Cool, we'll get that done going forward.
