### ISSUE TITLE
nemo-terminal: functionality is limited by (1) lack of position options, (2) failure to remember dimensions

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/nemo-extensions#240]
&nbsp;&nbsp;&nbsp;&nbsp;It seems to me that the nemo-terminal cannot be positioned where one wants it. No matter, I thought - I'll just hide it (by minimising it to nothing) and drag it out when I need it. Yet, new Nemo windows do not remember the size of the terminal pane.

&nbsp;&nbsp;&nbsp;&nbsp;The result of all this - unless I make some mistake - is as follows. 

1. Having a Nemo window simply display one's files (without a terminal in the way)
and  
2. having Nemo be able to display a terminal

are not compossible, i.e. one cannot have both. Surely that state of affairs is undesirable. I appreciate that sophisticating nemo-terminal would take some work. My point is: that work would be welcome.

**Comment by clefebvre** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
