### ISSUE TITLE
Duplicate & make link features available on Ubuntu but not on Debian

### ISSUE THREAD

**Issue by jean-christophe-manciot** [linuxmint/nemo-extensions#244]
nemo 3.6.2
nemo-extensions 3.6.0

Ubuntu 17.04 or 17.10
Debian 9 stretch

These features should be accessible on Debian with the right-click menu like on Ubuntu.
Or, am I missing something?

**Comment by mtwebster** [comment]
Select something, right-click, there should be a + sign on the upper right corner of the menu. Click it.

**Comment by jean-christophe-manciot** [comment]
Yes. Thanks.
