### ISSUE TITLE
nemo-extensions 3.6.0 build issue

### ISSUE THREAD

**Issue by rezso** [linuxmint/nemo-extensions#251]
nemo-preview searches xreader-document-1.5.0, xreader-view-1.5.0 .pc and gir files, but the real suffix is only 1.5, not 1.5.0.

**Comment by leigh123linux** [comment]
Fixed https://github.com/linuxmint/nemo-extensions/commit/52767dc75260935fc4c6a62f1b94c8c3798e5110
