### ISSUE TITLE
Provide installation instruction

### ISSUE THREAD

**Issue by frankgerhardt** [linuxmint/nemo-extensions#260]
Maybe these extensions would be really helpful. But I can't install them. I'm definitely not going through a git clone, compile etc. process. I have Debian 8. Where is the .deb file?

If you don't *distribute*  your code it is as if you wouldn't write it in the first place.

**Comment by leigh123linux** [comment]
Sorry we don't have time to write docs, if you want them you can write them.
It isn't our problem if Debian doesn't package them, maybe the lmde3 packages would work.

https://github.com/linuxmint/nemo-extensions/releases/tag/master.lmde3
