### ISSUE TITLE
nemo-share: modify Samba config to avoid error

### ISSUE THREAD

**Issue by ewangi** [linuxmint/nemo-extensions#280]
I wonder if it would be possible to incorporate the fix described at https://www.dedoimedo.com/computers/ubuntu-beaver-samba-shares.html in order to avoid an error accessing Windows shares.

The fix in question adds the following line anywhere in /etc/samba/smb.conf (creating the file if it doesn't exist):

`client max protocol = NT1`

**Comment by eli-schwartz** [comment]
Are these Windows XP boxes?

Don't use SMBv1, ever. https://blogs.technet.microsoft.com/filecab/2016/09/16/stop-using-smb1/

Also relevant: enabling this option is what allowed [WannaCry](https://en.wikipedia.org/wiki/WannaCry_ransomware_attack) to happen.

Also, nemo-share is not the thing which configures samba, it is a thing which uses the existing samba configuration. You should be talking to the samba developers or distribution packagers... but they'll laugh you off and tell you to stop reading bad blogs written by incompetent people who don't know what they're talking about.

**Comment by clefebvre** [comment]
This is being tackled upstream https://bugs.launchpad.net/ubuntu/+source/gvfs/+bug/1778322.
