### ISSUE TITLE
Add Peazip Extension

### ISSUE THREAD

**Issue by LinArcX** [linuxmint/nemo-extensions#281]
Hi. and thank you for this great job. in this moment there is only one extension for archiving. file-roller.
It'll be very usefull for users like me that use PeaZip As Archive-Tool. and integrate it with nemo for actions like: __Compress__, __Uncompress__, etc..

**Comment by kelebek333** [comment]
Hi, you can use following Nemo actions.

https://github.com/kelebek333/nemo-actions/tree/master/usr/share/nemo/actions

**Comment by LinArcX** [comment]
Thanks, i create an AUR Pkgbuild for it:
https://aur.archlinux.org/packages/nemo-peazip/
