### ISSUE TITLE
Error compiling nemo-preview

### ISSUE THREAD

**Issue by faidoc** [linuxmint/nemo-extensions#29]
Compiling nemo-preview in Arch Linux fails with:

config.status: error: po/Makefile.in.in was not created by intltoolize.

I don't know exactly what the problem is, but from a very old post (2009) talk about intltool and provide the following patch for their autogen.sh

https://launchpadlibrarian.net/20907980/awn-0.4-libtoolize-0.40.5-fix-1.patch

**Comment by leigh123linux** [comment]
Compiles fine here
