### ISSUE TITLE
Cannot compile nemo-python since switching to Meson.

### ISSUE THREAD

**Issue by CaerphillyMediaLtd** [linuxmint/nemo-extensions#291]
Hi, since you switched to Meson I get the following error when trying to build:

    ........................................... BUILDING: ./nemo-python
    ....
    ....
    dpkg-buildpackage: source package nemo-python
    dpkg-buildpackage: source version 3.9.0
    dpkg-buildpackage: source distribution UNRELEASED
    dpkg-buildpackage: source changed by Michael Webster <miketwebster@gmail.com>
    dpkg-buildpackage: host architecture amd64
    dpkg-source --before-build nemo-python
    fakeroot debian/rules clean
    dh clean
    dh_auto_clean
    dh_autoreconf_clean
    dh_clean
    dpkg-source -b nemo-python
    dpkg-source: info: using source format '3.0 (native)'
    dpkg-source: info: building nemo-python in nemo-python_3.9.0.tar.xz
    dpkg-source: info: building nemo-python in nemo-python_3.9.0.dsc
    debian/rules build
    dh build
    dh_testdir
    dh_update_autotools_config
    dh_autoreconf
    debian/rules override_dh_auto_configure
    make[1]: Entering directory '/home/levi/Documents/nemo-extensions/nemo-python'
    mkdir -p debian/build
    meson debian/build \
        --prefix=/usr \
        --libdir=/usr/lib/x86_64-linux-gnu \
        --buildtype=plain \
        -D gtk_doc=true \
        --errorlogs
    Directory already configured, exiting Meson. Just run your build command
    (e.g. ninja) and Meson will regenerate as necessary. If ninja fails, run ninja
    reconfigure to force Meson to regenerate.

    If build failures persist, manually wipe your build directory to clear any
    stored system data.

    To change option values, run meson configure instead.
    make[1]: Leaving directory '/home/levi/Documents/nemo-extensions/nemo-python'
    debian/rules override_dh_auto_build
    make[1]: Entering directory '/home/levi/Documents/nemo-extensions/nemo-python'
    ninja -C debian/build
    ninja: Entering directory `debian/build'
    ninja: no work to do.
    make[1]: Leaving directory '/home/levi/Documents/nemo-extensions/nemo-python'
    debian/rules override_dh_auto_test
    make[1]: Entering directory '/home/levi/Documents/nemo-extensions/nemo-python'
    # disable tests
    make[1]: Leaving directory '/home/levi/Documents/nemo-extensions/nemo-python'
    fakeroot debian/rules binary
    dh binary
    dh_testroot
    dh_prep
    debian/rules override_dh_auto_install
    make[1]: Entering directory '/home/levi/Documents/nemo-extensions/nemo-python'
    DESTDIR=/home/levi/Documents/nemo-extensions/nemo-python/debian/python-nemo \
    ninja -C debian/build install
    ninja: Entering directory `debian/build'
    [1/1] Installing files.
    Installing src/libnemo-python.so to /home/levi/Documents/nemo-extensions/nemo-python/debian/python-nemo/usr
    Installing /home/levi/Documents/nemo-extensions/nemo-python/debian/build/nemo-python.pc to /home/levi/Documents/nemo-extensions/nemo-python/debian/python-nemo/usr/lib/x86_64-linux-gnu/pkgconfig
    Running custom install script '/usr/bin/python3 /home/levi/.local/bin/meson --internal gtkdoc --sourcedir=/home/levi/Documents/nemo-extensions/nemo-python --builddir=/home/levi/Documents/nemo-extensions/nemo-python/debian/build --subdir=docs/reference --headerdirs=src --mainfile=nemo-python-ref.xml --modulename=nemo-python --mode=auto --content-files=/home/levi/Documents/nemo-extensions/nemo-python/docs/reference/entities.docbook.in --installdir=nemo-python --cflags=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 --ldflags=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro --cc=cc --ld=cc'
    Building documentation for nemo-python
    :0: warning: Value descriptions for NemoPythonDebug are missing in source code comment block.

    html/class-nemo-python-property-page.html:33: warning: no link for: 'class-gobject' -> (gobject.GObject).
    html/nemo-python-overview-methods.html:28: warning: no link for: 'method-nemo--menu-provider-emit-items-updated-signal' -> (Nemo.menu_provider_emit_items_updated_signal).
    html/nemo-python-overview-methods.html:29: warning: no link for: 'method-nemo--info-provider-update-complete-invoke' -> (Nemo.info_provider_update_complete_invoke).
    html/class-nemo-python-info-provider.html:192: warning: no link for: 'enum-nemo-python-operation-result--OPERATION_COMPLETE' -> (<code class="classname">Nemo.OperationResult.COMPLETE</code>).
    html/class-nemo-python-info-provider.html:199: warning: no link for: 'enum-nemo-python-operation-result--OPERATION_IN_PROGRESS' -> (<code class="classname">Nemo.OperationResult.IN_PROGRESS</code>).
    html/class-nemo-python-location-widget-provider.html:75: warning: no link for: 'class-gtkwindow' -> (<code class="classname">gtk.Window</code>).
    html/class-nemo-python-location-widget-provider.html:79: warning: no link for: 'class-gtk-widget' -> (<code class="classname">gtk.Widget</code>).
    html/class-nemo-python-column-provider.html:43: warning: no link for: 'class-info-provider' -> (<code class="classname">Nemo.InfoProvider</code>).
    html/class-nemo-python-menu-item.html:57: warning: no link for: 'property-nemo-python-menu-item--icon' -> (icon).
    html/class-nemo-python-menu-item.html:62: warning: no link for: 'property-nemo-python-menu-item--label' -> (label).
    html/class-nemo-python-menu-item.html:67: warning: no link for: 'property-nemo-python-menu-item--menu' -> (menu).
    html/class-nemo-python-menu-item.html:72: warning: no link for: 'property-nemo-python-menu-item--name' -> (name).
    html/class-nemo-python-menu-item.html:77: warning: no link for: 'property-nemo-python-menu-item--priority' -> (priority).
    html/class-nemo-python-menu-item.html:82: warning: no link for: 'property-nemo-python-menu-item--sensitive' -> (sensitive).
    html/class-nemo-python-menu-item.html:87: warning: no link for: 'property-nemo-python-menu-item--tip' -> (tip).
    html/class-nemo-python-file-info.html:33: warning: no link for: 'class-ginterface' -> (gobject.GInterface).
    html/class-nemo-python-menu-provider.html:166: warning: no link for: 'method-nemo-menu-provider--emit_items_updated_signal' -> (Nemo.menu_provider_emit_items_updated_signal).

    make[1]: Leaving directory '/home/levi/Documents/nemo-extensions/nemo-python'
    dh_installdocs
    dh_installchangelogs
    dh_perl
    dh_link
    dh_strip_nondeterminism
    dh_compress
    dh_fixperms
    debian/rules override_dh_strip
    make[1]: Entering directory '/home/levi/Documents/nemo-extensions/nemo-python'
    dh_strip --dbg-package=nemo-python-dbg
    dh_strip: debug package nemo-python-dbg is not listed in the control file
    debian/rules:24: recipe for target 'override_dh_strip' failed
    make[1]: *** [override_dh_strip] Error 25
    make[1]: Leaving directory '/home/levi/Documents/nemo-extensions/nemo-python'
    debian/rules:6: recipe for target 'binary' failed
    make: *** [binary] Error 2
    dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2

Running ubuntu 16.04.

**Comment by mtwebster** [comment]
Ah sorry. I had renamed the packages then reverted it. I missed one changed it looks like. Change the rules file under dh_strip to python-nemo-dbg rather than nemo-python-dbg

**Comment by mtwebster** [comment]
I can’t do it right now. I’ll fix a bit later.
