### ISSUE TITLE
[Support] Extensions not running with Python 3

### ISSUE THREAD

**Issue by dglava** [linuxmint/nemo-extensions#292]
I've seen that some extensions have been ported to Python 3. I decided to try them, but I'm getting this error

```
Traceback (most recent call last):
  File "/usr/share/nemo-python/extensions/nemo-media-columns.py", line 26, in <module>
    from urllib import parse
ImportError: cannot import name parse
```
Adding a `print(sys.version)` at the beginning revealed that it's running the script with Python 2. The shebang is pointing to Python 3, i.e.: `#!/usr/bin/python3`. What am I doing wrong?

**Comment by mtwebster** [comment]
For python extensions like that one, you also need to upgrade nemo-python (which is sort of the gateway interface for nemo to use these extensions.)

**Comment by dglava** [comment]
That solved it, thank you for the quick answer.
