### ISSUE TITLE
nemo-terminal wrong depend

### ISSUE THREAD

**Issue by misterhsp** [linuxmint/nemo-extensions#304]
probably typo. control, line 16.

...

**Comment by leigh123linux** [comment]
Not enough info.

**Comment by misterhsp** [comment]
nemo-python  <-->  python-nemo

python-nemo is wrong

**Comment by leigh123linux** [comment]
python-nemo is correct, see

https://github.com/linuxmint/nemo-extensions/blob/master/nemo-python/debian/control#L14

and

https://github.com/linuxmint/nemo-extensions/blob/master/nemo-terminal/debian/control#L16

**Comment by misterhsp** [comment]
I see it differently, a package python-nemo I do not find in the repo. Anyway, nemo-terminal cannot be built like this. If I rename it in the control it works. But we don't want to argue :)
