### ISSUE TITLE
[nemo-media-columns] "Length" column doesn't work on LM 19.1

### ISSUE THREAD

**Issue by ninosanta** [linuxmint/nemo-extensions#306]
```
 * Cinnamon version:  4.0.8
 * Distribution: Linux Mint 19.1 64 bit
 ```

**Issue**
When I was on LM 19 the "length" column in the list view of nemo -obtained thanks to the _nemo-media-columns_ extension- worked fine. Now, on a clean installation of LM 19.1 it doesn't show the medias length anymore

**Comment by jonahsullivan** [comment]
I found a missing dependency. I installed mediainfo and it started working.

sudo apt install mediainfo

**Comment by ninosanta** [comment]
@jonahsullivan, thanks for the help. It worked!
