### ISSUE TITLE
[Feature Request] nemo-magenta-plugin

### ISSUE THREAD

**Issue by MegaV0lt** [linuxmint/nemo-extensions#315]
I would realy like to have a "Magenta Cloud" plugin for nemo

It should be lie the dropbox or nextcloud plugin. It should be able to create share links
sadly the App for MagentaCloud is only for Win, Mac and Android...

REF:
https://cloud.telekom-dienste.de/
https://cloud.telekom-dienste.de/software-apps#magentacloud-app

**Comment by leigh123linux** [comment]
Unlike dropbox or nextcloud they don't support linux, feel free to reopen once they provide a linux client.

**Comment by MegaV0lt** [comment]
I know. Is it not possible to use there api:
https://cloud.telekom.de/de/infrastruktur/open-telekom-cloud/tutorials/apis-opentelekomcloud

I am afraid that's too complicated for me
