### ISSUE TITLE
[feature request] Box Drive support

### ISSUE THREAD

**Issue by faelv** [linuxmint/nemo-extensions#316]
Just like the DropBox extension but for [Box](https://github.com/box)

**Comment by ferdnyc** [comment]
I didn't think Box _had_ a Linux-compatible sync daemon, a recollection that [the Box Drive download page](https://www.box.com/resources/downloads/drive) and [the Box sync-settings page](https://app.box.com/settings/sync) both bear out.

(The file manager extension is useless without the daemon, and the APIs to interface it. Even the nemo-dropbox code comes from the Dropbox team themselves. The Box developers have written no similar extension for Nemo/Nautilus/anything-Linux.)

How would nemo-extensions support something that doesn't exist?
