### ISSUE TITLE
You create fine plugins but you dont create an installation readme 

### ISSUE THREAD

**Issue by ypersyntelykos** [linuxmint/nemo-extensions#321]

**Comment by ypersyntelykos** [comment]
You create fine plugins but you dont create an installation readme.txt
For users Linux mint 19..

**Comment by smurphos** [comment]
Have you tried searching for `nemo-` in Software Manager, Synaptic or with `apt search nemo-`

**Comment by macsimski** [comment]
and how should i know that, except that you tell me? is this written somewhere we did not look or is this "Obvious knowledge ©".  maybe just put it in the readme for the files for the dumber ones like us. :-)

**Comment by smurphos** [comment]
The problem with putting instructions here is Nemo (and Cinnamon) are not just used in Mint (or even in just Ubuntu or Debian based distros) - they are used in Fedora, Arch, Gentoo etc, etc. - and there aren't  one size fits all install instructions for the extensions that covers all those different distros.  

Anyway the advise stands - For Mint users all the extensions in this repo are packaged for install in the Mint repos.

**Comment by macsimski** [comment]
maybe just put that in the readme? (including the mint bit)

**Comment by johndpope** [comment]
I wasted about  an hour attempting to build this thing on ubuntu 22.04 as I prefer the nemo client than the files in ubuntu. If it's impossible to add extensions to nemo for ubuntu - just say it - save me the time.

**Comment by leigh123linux** [comment]
You are free to write a readme and submit as a pr.
