### ISSUE TITLE
[nemo-dropbox] import gobject fix

### ISSUE THREAD

**Issue by marguerite** [linuxmint/nemo-extensions#33]
Patch: https://build.opensuse.org/package/view_file/X11:Cinnamon:Factory/nemo-dropbox/nemo-dropbox-2.0.0-import-gobject.patch?expand=1

on newer version of gobject/girepository-introspection, such python usage:

"import gobject"

will trigger an error. 

ImportError: could not import gobject (error was: ImportError('When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject".',))

So if you installed this plugin with nemo, nemo can't start.

it should be replaced with 

"from gi.repository import GObject"

**Comment by monsta** [comment]
should've been closed long ago...
