### ISSUE TITLE
nemo-python: Host-application detection from within the Python code?

### ISSUE THREAD

**Issue by ferdnyc** [linuxmint/nemo-extensions#330]
[GSConnect](https://github.com/andyholmes/gnome-shell-extension-gsconnect) is a Gnome Shell implementation of the [KDE Connect](https://community.kde.org/KDEConnect) protocol for local-network communication between the PC and Android phones running the corresponding app.

Because the integrations include file transfer in both directions, GSConnect includes a Nautilus extension implemented in `nautilus-python` that provides context-menu options to initiate transfer of selected files. We were recently asked (andyholmes/gnome-shell-extension-gsconnect#579) to add Nemo support to the extension.

Because `nemo-python` provides all of the same interfaces, just under a different name, this is ostensibly a fairly trivial request to meet. I've [managed to generalize](https://github.com/andyholmes/gnome-shell-extension-gsconnect/pull/580/commits/b4f846e5c7a5aa6e0af2214a3e883703aeeae497) the code so that the only difference between the code as installed in either Nautilus and Nemo is a variable at the top of the file that sets which application is hosting the extension.

But that's where I'm stuck. I haven't been able to figure out any reliable method for the code to _automatically_ detect whether it's being hosted by Nemo or Nautilus, and import the correct interfaces accordingly without the need to set that variable. I'd really like to lick that problem, as it would mean we can simply use the same extension file installed into both `$HOME/.local/share/{nautilus,nemo}-python/extensions/`, instead of having to maintain two files and keep them in sync, even if they only differ by one line.

Any ideas? The only potential solutions I've been able to find so far are references in the code to an environment variable called `INSIDE_NEMO_PYTHON`, but other than explicitly **unsetting** that variable nothing ever seems to make use of it, and in my testing it _does not_ appear to be set in the environment of the running Python code.

https://github.com/linuxmint/nemo-extensions/blob/373855405483361a321d6dbc6fe48db062ba3f8f/nemo-python/src/nemo-python.c#L202-L206

(My current non-solution):
```py
# Force Nautilus integration, for testing
FILE_MANAGER="Nautilus"

import gi
from gi.repository import Gio, GLib, GObject

if "Nemo" in FILE_MANAGER:
    gi.require_version('Nemo', '3.0')
    from gi.repository import Nemo as FileManager
elif "Nautilus" in FILE_MANAGER:
    gi.require_version('Nautilus', '3.0')
    from gi.repository import Nautilus as FileManager
```

...And then all the rest of the code refers to `FileManager`, host-application-agnostically.

**Comment by ferdnyc** [comment]
I mean, I suppose there's always the **#Code_l_Will_Never_Admit_To_Writing** method, something like:

```py
if "nemo" in os.path.dirname(os.path.realpath(__file__)):
    gi.require_version('Nemo', '3.0')
    from gi.repository import Nemo as FileManager
elif "nautilus" in os.path.dirname(os.path.realpath(__file__)):
    gi.require_version('Nautilus', '3.0')
    from gi.repository import Nautilus as FileManager
```

**Comment by mtwebster** [comment]
What about just checking the process name?  I’ll think about this some more, that was just an initial thought.

**Comment by ferdnyc** [comment]
@mtwebster 

Hmmm, that could work. A quick test reveals that `sys.executable` is `/usr/bin/python`, but `sys.argv[0]` is indeed `nemo`.

Any opinions how safe it is to rely on that? I'm definitely much _less_ confident in assuming the Nautilus end of that equation will remain indefiinitely reliable, what with D-Bus based launching and various components being renamed AppStream-ey things like `org.Gnome.Nautilus`...

**Comment by ferdnyc** [comment]
### \#WAT.

```console
$ head $HOME/.local/share/nemo-python/extensions/nemo-gsconnect.py
# Force Nemo integration, for testing
FILE_MANAGER="Nemo"

import gettext
import locale
import os.path
import sys

print("argv: ", sys.argv, "sys.executable: ", sys.executable) 


$ nemo -q                                                         

argv:  ['nemo'] sys.executable:  /usr/bin/python3
Initializing nemo-dropbox 4.0.0


$ head $HOME/.local/share/nautilus-python/extensions/nautilus-gsconnect.py 
# Force Nautilus integration, for testing
FILE_MANAGER="Nautilus"

import gettext
import locale
import os.path
import sys

print("argv: ", sys.argv, "sys.executable: ", sys.executable) 

$ nautilus -q

argv:  ['thunar'] sys.executable:  /usr/bin/python3
Initializing nautilus-dropbox 2019.01.31
```

<H4><b><code>argv:  ['thunar']</code></b> 😲</H4>

**Comment by ferdnyc** [comment]
Thunar _**isn't even installed**_ on my machine!
```console
$ which thunar
/usr/bin/which: no thunar in (/home/ferd/perl5/bin:/home/ferd/.local/lib:/home/ferd/.local/bin:
/usr/libexec/python3-sphinx:/usr/lib64/qt-3.3/bin:/usr/lib/qtchooser:/usr/share/Modules/bin:
/usr/local/cuda/bin:/usr/lib64/ccache:/home/ferd/.cargo/bin:/usr/local/bin:/usr/local/sbin:
/usr/bin:/usr/sbin:/home/ferd/bin:/home/ferd/.composer/vendor/bin:/home/ferd/.linuxbrew/bin)
```

**Comment by ferdnyc** [comment]
I ended up going with "Check `sys.argv[0]` for 'nemo', otherwise assume we're running under Nautilus", due to the latter's apparent schizophrenia. Seems to work well enough. Thanks!
