### ISSUE TITLE
nemo-dropbox package stops upgrade/install asking for confirmation

### ISSUE THREAD

**Issue by marcinbojko** [linuxmint/nemo-extensions#331]
Using any method to add nemo-dropbox (apt install, ansible/apt) whole process stops waiting for confirmation
```
In order to use Dropbox, you must download the proprietary daemon. (y/n)
```
This makes unnatended/ansible instalation hard to execute, at least for me I wasn't able to find a safe/secure way to supress this message and continue instalation.

Proposed solutions
- assume-yes as default parameter
- download-daemon as boolean parameter
- skip-asking 

Package version: nemo-dropbox/tina,now 4.2.0+tina

**Comment by leigh123linux** [comment]
File the issue against the dropbox package as that provides that dialog.
