### ISSUE TITLE
How to compile & install on fedora 30 (cinnamon)??

### ISSUE THREAD

**Issue by csurf** [linuxmint/nemo-extensions#338]
I'm running nemo on a Fedora 30 spin w/ cinnamon. Apparently, it doesn't provide the 'nemo-share' extension, and there's no way to install it via dnf package manager.

I'd like to compile & install it myself, but there aren't any actual install instructions in the nemo-extensions repo, and it looks like it relies on dpkg to build. Can someone pls help me understand how to do a generic build for my platform (x86_64 fedora 30) and how to install it into nemo?

**Comment by leigh123linux** [comment]
I wouldn't waste time trying to compile nemo-share, it didn't work last time I tried to package it for fedora.

**Comment by leigh123linux** [comment]
To build

./autogen.sh
./configure --prefix=/usr
make
sudo make install

Confirm it doesn't work and remove

sudo make uninstall

**Comment by rh-jelabarre** [comment]
My question is just _what_ is broken with nemo-share on Fedora?  It must be making some Debian/Ubuntu assumptions (the same way projects like Anbox do).
