### ISSUE TITLE
Error on clicking on "Show the files" after extracting a file from a compressed folder

### ISSUE THREAD

**Issue by BrunoNZ** [linuxmint/nemo-extensions#347]
There is a bug in the process of extracting a file from a compressed folder and then clicking on "Show the files", using file-roller. The program tries to find the extracted file within a path containing the compressed folder name, even if only the file was extracted and not the whole folder. It returns an error because the path doesn't exist and the file is not shown. If the whole folder is extracted the action works fine.

Tested on: Mint Cinnamon 19.2 and 19.3 beta
File-Roller: 3.28.0
Nemo: 4.4.2

![Peek 2019-12-12 12-33](https://user-images.githubusercontent.com/1660320/70726770-60774200-1cdd-11ea-82c2-4cbb2821ea82.gif)

**Comment by clefebvre** [comment]
Ah right.. sorry, I thought it was an issue with the nemo action. This is upstream from us then, it's in file-roller itself. We're using 3.28 though, I'd suggest to check their latest version (either by compiling it or using a rolling distribution) before submitting this as a bug report to GNOME.

**Comment by BrunoNZ** [comment]
Ok, no problem at all, Clem. I thought so too. I will do some more tests and then report it to them.
