### ISSUE TITLE
Please kindly add "nemo-wipe" for Fedora repositories.

### ISSUE THREAD

**Issue by Nokia808** [linuxmint/nemo-extensions#349]
Hi. 1st I would like to thank you very much for adding "nemo-seahorse" to Fedora repositories.

Dear can you, kindly, also, adding "nemo-wipe" for Fedora repositories ? I found the following link which indicates that there is such extension:

https://github.com/linuxmint/Cinnamon/issues/3183

Is this request enough or I have to create corresponding one on RedHat bugzilla also ?

**Comment by leigh123linux** [comment]
Sorry that extension doesn't exist within nemo-extensions.
I don't have the time to package anything more for fedora repo, someone else will need to do it and submit review requests to redhat bugzilla.
