### ISSUE TITLE
Nemo terminal(F4) doesn't paste using the keyboard to the right-pane terminal if there are 2 panes

### ISSUE THREAD

**Issue by a-bentofreire** [linuxmint/nemo-extensions#364]
```
 * Nemo version: nemo 3.8.5  (but also happened in all previous versions)
 * Distribution - Linux Mint 19  (but also happened in all previous versions)
 ```

**Issue**
If I have nemo with 2 panes, and with the nemo terminal open (F4),
and the right-pane terminal is selected, and I paste using (ctrl+shift+V),
it pastes to the left-pane terminal instead of the right-pane terminal.

**Steps to reproduce**
- Open Nemo
- Select a file and copy it.
- Open 2 panes (F3).
- Open nemo terminals (F4).
- Select the right-pane terminal.
- Paste using ctrl+shift-V.

**Expected behaviour**
- Paste on the right-pane nemo terminal.

**Other information**

**Comment by xenopeek** [comment]
I can't reproduce this with Nemo 4.6.4; it copies the file location in the right-pane terminal as expected.

**Comment by a-bentofreire** [comment]
I'm now using the Nemo 4.6.5 under Linux Mint 20,
and the bug still holds, this time, it's on the left pane.


## Steps to reproduce

    - Copy any text
    - Open Nemo
    - Open 2 panes (F3).
    - Open nemo terminals (F4).
    - Select the left-pane terminal.
    - Paste using ctrl+shift-V.

**Comment by xenopeek** [comment]
This I can reproduce. I'd insert before the last step that you can even type in the left-pane terminal to confirm it has input focus but pressing cltr+shift+v still pastes to the right-pane.

Would you make a new issue from your above comment? I think otherwise we risk crossing wires.

**Comment by a-bentofreire** [comment]
Sure.
I have just created a new issue.

[Nemo terminal(F4) doesn't paste using the keyboard to the left-pane terminal if there are 2 panes](https://github.com/linuxmint/nemo-extensions/issues/384)
