### ISSUE TITLE
nemo python doesn't seem to work in mint 20 nemo version - 4.6.4

### ISSUE THREAD

**Issue by sk-Prime** [linuxmint/nemo-extensions#368]
i tried all the examples but nothing seems to work. when i click on a script it produce text file of imported module in current directory. for example md5sum-property-page.py produce two files named urrlib and hashlib. nowhere i cant find any md5 value.

can you provide a simple example like hello world of nemo python , thus i can check it.

thanks in advance

**Comment by leigh123linux** [comment]
None of the examples were ported to python3, try editing with these changes

```
--- md5sum-property-page.py	(original)
+++ md5sum-property-page.py	(refactored)
@@ -1,5 +1,5 @@
 import hashlib
-import urllib
+import urllib.request, urllib.parse, urllib.error
 
 from gi.repository import Nemo, Gtk, GObject
 
@@ -18,7 +18,7 @@
         if file.is_directory():
             return
 
-        filename = urllib.unquote(file.get_uri()[7:])
+        filename = urllib.parse.unquote(file.get_uri()[7:])
 
         self.property_label = Gtk.Label('MD5Sum')
         self.property_label.show()
```

**Comment by sk-Prime** [comment]
thanks for the ported version. unfortunately, nothing happen.
i added, `with open(path+"/test.txt",'w') as test: test.write()` this line under the import lines. i expected to have a text file at given path but no luck. as if the code doesn't run at all.

**Comment by sk-Prime** [comment]
if you make a python script executable `+x` , and then double click on that script then press run it will not run and make text file. same thing happen to nemo python script.

**Comment by sk-Prime** [comment]
using shebang solve the problem. `#!/usr/bin/env python3`
