### ISSUE TITLE
HOW CAN WE INSTALL THIS EXTENSIONS ON DEBIAN BUSTER. NEED A TUTO

### ISSUE THREAD

**Issue by pzim-devdata** [linuxmint/nemo-extensions#371]
Hello,
Could you, please, explain me how does it works step by step ?
I have Nemo 3, and I use Debian Buster Cinnamon
I have tried to execute setup.py or other commands but it doesn't works.
In which folder should I put extensions ?
Is there a tuto ?

Thanks !

**Comment by Jeremy7701** [comment]
nemo 3 is an old version of nemo.
Current stable version is 4.6.5 - the source is at [https://github.com/linuxmint/nemo](https://github.com/linuxmint/nemo)
There should be a version for LMDE4 somewhere that is only based on Debian packages and nothing based on the Ubuntu modifications of Debian.
Good luck!

**Comment by pzim-devdata** [comment]
Ok thank you for your help. I use Debian with Cinnamon. I think I will wait for a stable version of Nemo 4 when it will be released.

Thanks !

**Comment by Jeremy7701** [comment]
You might be interested in LMDE which is a Mint Debian Edition - based on Buster and available from [https://www.linuxmint.com/download_lmde.php](https://www.linuxmint.com/download_lmde.php).
It will give you a Debian Cinnamon distro with some Mint customisation - worth a try as a VM anyway.

**Comment by pzim-devdata** [comment]
I have been doing a very complex installation of Debian for many years, so I think I will wait for Debian 11 Bullseye. It will have the stable version of Nemo 4 with it. Thank you ! :-)
