### ISSUE TITLE
.deb installs as broken on ubuntu 20.04

### ISSUE THREAD

**Issue by AquariusPower** [linuxmint/nemo-extensions#375]
first I got this error: 
"dpkg-buildpackage: error: failed to sign .dsc file" but the .deb was created!!! so just ignore it...

when trying to install it:
gdebi-gtk nemo-compare_4.6.0_all.deb
it installs but in a broken state, but will run anyway.

To prepare a valid .deb for ubuntu 20.04 you have to:
at `nemo-compare/debian/control` (and all other control files you need), modify it where it is written:
`python-nemo`
to:
`nemo-python`

and now you will get  a valid .deb :)

**Comment by AquariusPower** [comment]
I will close this as it has the answer, feel free to reopen if it can be fixed in a better way :)

**Comment by mtwebster** [comment]
The signing error, yes that can always be ignored if you're building for yourself.  There's a flag for dpkg-buildpackage that will suppress it, but I wouldn't bother.

The second, python-nemo is actually the correct package if you're building these from git.

In mint the package is called python-nemo (If you build this from the nemo-extensions source, this is what it's called). In debian, and hence in ubuntu, they decided to rename it, so we have this fun conflict.

If you build nemo-compare (or any python nemo extensions) from *git*, build python-nemo from git also. (And remove nemo-python).

**Comment by AquariusPower** [comment]
oh I get it, build the dependency too.
This project was the only one that worked on 20.04, I could not find any working ppa or etc.
Btw, I was going to propose a dependency configuration as `nemo-python | python-nemo` but I would need to know nemo-python version, despite now I think they are both the same version :)
