### ISSUE TITLE
segmentation fault in the nemo-terminal

### ISSUE THREAD

**Issue by shres58tha** [linuxmint/nemo-extensions#397]
this is a severe fault that i noticed after the new update from nemo for linuxmint 20 ulyssa.
even the nemo-desktop failed to load. while running nemo in the terminal gave the segmentation fault.
removed the cinnamon and also purged nemo* n then reinstalled still same fault.
finally has to remove the extension to get the desktop and nemo file manager working.

**Comment by leigh123linux** [comment]
Closed https://github.com/linuxmint/nemo-extensions/commit/7eaed06b22aea64150a408da460e6d1f132086c7
