### ISSUE TITLE
Gnome archive handler language problem

### ISSUE THREAD

**Issue by 986Geir** [linuxmint/nemo-extensions#400]
I am using Ubuntu Budgie and it comes with the Gnome archive handler.
When I download a zip folder, and open it with the archive handler, it does not understand the native Norwegian letters. Gives a file name where the native letters are changed to something cryptic.

Have found that the ARK archiver works fine as an alternative.
Would love to use the Gnome version if it is a fix for the problem.

**Comment by mtwebster** [comment]
This repository is for extensions for the Nemo file manager - are you sure you're in the right place?

It sounds like the one you're having trouble with translations on is file-roller - maybe open an issue here: https://gitlab.gnome.org/GNOME/file-roller.

I'm not familiar with Ubuntu Budgie or budgie in general. It looks like ARK uses a completely different toolkit (and a lot of different supporting packages) than file-roller, and most desktops try to settle upon a single one (though users are free to install anything they want of course).

Either way, we can't do much here.

Are these files you created? If so, what is your system locale - are you using utf-8 (type `locale`).

**Comment by 986Geir** [comment]
Ok, was sent to this place at the Budgie forum and said to tip you guys.
Does not know if i am using utf-8. All works fine with the language on the computer. Only problem is when I download a bunch of files from Outlook or Teams to a compressed folder. The standard Ubuntu file archiver cannot pack out with correct file name. Have found that the ARK does, so will use that instead. Sorry to use your time if I am at the wrong place.
