### ISSUE TITLE
Nemo git plugin?

### ISSUE THREAD

**Issue by sebastiansam55** [linuxmint/nemo-extensions#403]
I see in the google search results that there was a plugin for a much older version of nemo, is there a more current one?

Not sure how the old one functioned but I was looking for something similar to the NERDTree git plugin where it would show a icon on each file in a git folder that would display its status in the repo. 

Kind of like the Dropbox plugin but for git.

thanks.

**Comment by ItzSwirlz** [comment]
*sigh* there was some talk about this.. then we had nemo-rabbitvcs and all. I believe upstream rabbitvcs maintainers have a nemo package

**Comment by sebastiansam55** [comment]
In case anyone stumbles upon this in the future here is where I was able to install the plugin

https://github.com/rabbitvcs/rabbitvcs/tree/master/clients/nemo

Rabbitvcs really needs to reconsider their branding lol, I would think that the majority of people looking for something like they provide would search for the specific name of the software not "VCS"
