### ISSUE TITLE
Missing dependencies for Ubuntu Budgie 20.04

### ISSUE THREAD

**Issue by rbreaves** [linuxmint/nemo-extensions#407]
I installed the deb file, but had to add a 3rd party repo and install an additional package still.

sudo add-apt-repository ppa:savoury1/xapps
sudo apt update
sudo apt install gir1.2-gtksource-4.0
sudo apt install ./nemo-preview_4.8.0_amd64.deb

If there's a better method to go about installing these extensions I'd like to know about it.

**Comment by leigh123linux** [comment]
Ask your distro to package them.
