### ISSUE TITLE
nemo-terminal : Follow navigation and "pending" command

### ISSUE THREAD

**Issue by FoxXav** [linuxmint/nemo-extensions#412]
Hi,

I configure nemo-terminal so it follow nemo directory navigation. I notice that there is an issue when you navigate directory when you add already started to type a command but not executed it.
if you write :
[~] > echo test

without validating (press enter) and you change directory the command is executed when the terminal actually change the directory and more, the command is executed after each directory change that follow without typing anything new in the terminal.
The command seems to be rewrite in the line but is "entered" which explain the empty command and the executed command.

Also as it appear in the screenshot (with bash this time) the cd command sometime display and we can also see the "echo" command that is put on the new dir line command and executed.

I though that the command should not be executed but only rewrited in the terminal in the new directory (the issue appear with all shell I test sh/bash and zsh with or without formatting script like powerlevel10k).

Hope someone could help.

See you.

https://user-images.githubusercontent.com/35500657/120457123-7f1c3d80-c396-11eb-9545-0e76789cd9f3.mp4

![Capture d’écran du 2021-06-02 11-34-45](https://user-images.githubusercontent.com/35500657/120457258-978c5800-c396-11eb-9027-259bd1d65660.png)

**Comment by viniciusbm** [comment]
Please see pull request #417.


https://user-images.githubusercontent.com/11576083/126083447-4df86549-5f38-4e93-988f-aed272474396.mp4

**Comment by FoxXav** [comment]
Nice, thank you
