### ISSUE TITLE
Nemo archives wrong symbols used

### ISSUE THREAD

**Issue by MegaV0lt** [linuxmint/nemo-extensions#438]
Mint Cinnamon 20.3 and Nemo in archives there is used old icons:
![Auswahl_145](https://user-images.githubusercontent.com/2804301/148690655-10e68c1a-3d34-4976-a527-4da0a84d565c.png)

**Comment by leigh123linux** [comment]
Nemo in archives = file-roller
file-roller uses CSD  https://wiki.gnome.org/Initiatives/CSD


![image](https://user-images.githubusercontent.com/1299302/148693104-5cb905cb-97b6-4c50-8076-e45445180cc5.png)
