### ISSUE TITLE
nemo-preview clashes with mate-panel libwnck tooltip 

### ISSUE THREAD

**Issue by minuxlintebiandedition** [linuxmint/nemo-extensions#441]
Linuxmint mate 20.2 live iso 

Installed nemo-preview.
Expected it to work like it does in cinnamon, which also uses mate-panel and libwnck.
nemo-preview should suppress libwnck tooltips to prevent clashing.

Also reproduced problem in lmde5 32 and 64 with mate-panel and nemo-preview.

**Comment by mtwebster** [comment]
https://github.com/mate-desktop/mate-panel/issues/534
