### ISSUE TITLE
Issues installing nemo terminal.

### ISSUE THREAD

**Issue by linusrg1** [linuxmint/nemo-extensions#457]
I used the command ```python setup.py install``` to install nemo-terminal. (I cannot use the deb as I am on fedora) and now nemo refuses to open, shooting out this error. 

(nemo:16239): GLib-GIO-ERROR **: 20:16:30.409: Settings schema 'org.nemo.extensions.nemo-terminal' is not installed
Trace/breakpoint trap (core dumped)

**Comment by leigh123linux** [comment]
Use.

```
sudo dnf install nemo-terminal
```

**Comment by linusrg1** [comment]
Thanks.
