### ISSUE TITLE
nemo-preview is bugged in wayland

### ISSUE THREAD

**Issue by ruZeph** [linuxmint/nemo-extensions#482]
```
Nemo version- nemo 5.6.4
Issue with window manager
OS: Fedora 38 Workstation
Graphics - Intel UHD IGPU
64 bit
 ```

**Issue**
nemo-preview does not work on Wayland session. It throws the following error:

`(nemo:21512): Gdk-CRITICAL **: 13:22:17.241: gdk_x11_window_get_xid: assertion 'GDK_IS_X11_WINDOW (window)' failed`

**Steps to reproduce**
1. Install nemo and nemo-preview on any Wayland session.
2. Run nemo and try to preview anything by hitting spacebar.

**Expected behaviour**
The selected file preview is shown.

**Other information**
The file preview works okay on X11.

**Comment by molove** [comment]
I came across this [https://reddit.com/r/pop_os/comments/iw2y1p/install_and_enable_nemopreview_in_pop_os/](url) which recommended editing /usr/bin/nemo-preview and adding export GDK_BACKEND=x11 before any of the export lines if using Wayland.
