### ISSUE TITLE
hi, im trying to install the extensions for nemo on ubuntu.

### ISSUE THREAD

**Issue by DOOMMARINE117** [linuxmint/nemo-extensions#499]
Hi, im trying to install the nemo extensions. but the ones i want our media colums, audiotab, preview, image convertor and emblems.

**Comment by leigh123linux** [comment]
This isn't a bug, either look for a PPA repo or ask on ubuntu forum for help.

**Comment by DOOMMARINE117** [comment]
i moved on to neptune os aka base on debian
