### ISSUE TITLE
Nemo seahorse "use a shared passphrase" fails.

### ISSUE THREAD

**Issue by CamieleonGitHub** [linuxmint/nemo-extensions#505]
When I try to encrypt a file using the GUI in Cinnamon and select _"use a shared passphrase"_ I get the following output:
```nemo
EXEC: nemo-seahorse-tool --encrypt 'file:///home/username/Desktop/Test.txt'

** (nemo-seahorse-tool:9546): WARNING **: 16:05:33.083: couldn't load ui file: Failed to open file “PKGDATADIR/uiseahorse-progress.xml”: No such file or directory

** (nemo-seahorse-tool:9546): WARNING **: 16:05:33.083: could not find widget progress for seahorse-progress.xml

(nemo-seahorse-tool:9546): Gtk-CRITICAL **: 16:05:33.083: gtk_window_set_icon_name: assertion 'GTK_IS_WINDOW (window)' failed

** (nemo-seahorse-tool:9546): WARNING **: 16:05:33.083: could not find widget progress for seahorse-progress.xml

** (nemo-seahorse-tool:9546): CRITICAL **: 16:05:33.083: seahorse_widget_get_toplevel: assertion 'widget != NULL' failed

** (nemo-seahorse-tool:9546): WARNING **: 16:05:33.083: could not find widget progress for seahorse-progress.xml

(nemo-seahorse-tool:9546): Gtk-CRITICAL **: 16:05:33.083: gtk_window_move: assertion 'GTK_IS_WINDOW (window)' failed

** (nemo-seahorse-tool:9546): WARNING **: 16:05:33.083: could not find widget progress for seahorse-progress.xml

** (nemo-seahorse-tool:9546): CRITICAL **: 16:05:33.083: progress_show: assertion 'w != NULL' failed
```
It seems **'uiseahorse-progress.xml'** in the first warning gives a clue with the **'ui'** prefix missing a **'/'** in between.
This is the actual file: /usr/share/nemo-seahorse/ui/seahorse-progress.xml

I suspect that one of these is the culprit:
https://github.com/linuxmint/nemo-extensions/blob/master/nemo-seahorse/tool/seahorse-widget.c#L206-L207
https://github.com/linuxmint/nemo-extensions/blob/master/nemo-seahorse/meson.build#L73

**Comment by CamieleonGitHub** [comment]
I use the arch linux package: https://archlinux.org/packages/extra/x86_64/nemo-seahorse/
I hope me using arch linux won't be too much of an obstacle in troubleshooting this problem.

**Comment by leigh123linux** [comment]
@ArchangeGabriel  The archlinux packaging is broken.

**Comment by ArchangeGabriel** [comment]
@CamieleonGitHub I’m not doing any packaging currently, so you should report your issue to https://gitlab.archlinux.org/archlinux/packaging/packages/nemo-extensions/-/issues/new if you want someone to look into it.
