### ISSUE TITLE
nemo-terminal works only for root

### ISSUE THREAD

**Issue by qrockz** [linuxmint/nemo-extensions#506]
I've installed the nemo-terminal extension. 

When I launch nemo with root then this extension works.
But launching as normal user the terminal it won't launch.

`nemo 5.6.4`
```
cat /etc/*-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=21.1
DISTRIB_CODENAME=vera
DISTRIB_DESCRIPTION="Linux Mint 21.1 Vera"
NAME="Linux Mint"
VERSION="21.1 (Vera)"
ID=linuxmint
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 21.1"
VERSION_ID="21.1"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=vera
UBUNTU_CODENAME=jammy

```

**Comment by claudiux** [comment]
Have you configured nemo-terminal to appear at start-up? Try to click on a file, then press F4.

**Comment by qrockz** [comment]
> Have you configured nemo-terminal to appear at start-up? Try to click on a file, then press F4.

"Visible by default" is enabled. Clicked on a file, directory - still not working.

**Comment by claudiux** [comment]
Then it should work in your next session.

**Comment by claudiux** [comment]
> Sorry 4 wasting ur time

Don't worry.
