### ISSUE TITLE
Fileroller crashes when I try to open a rar file

### ISSUE THREAD

**Issue by scaforchio** [linuxmint/nemo-extensions#535]
In linux mint 22 updated from the previous version (where I didn't have the problem) when I try to open a rar file with file-roller I get the following error:
(file-roller:3807): GLib-CRITICAL **: 09:27:12.409: g_strchomp: assertion 'string != NULL' failed
Segmentation error (core dump created)

**Comment by mtwebster** [comment]
Please supply crash info if possible:
https://projects.linuxmint.com/reference/git/bugs/mintreport-crash-info.html

**Comment by scaforchio** [comment]
I solved it by forcing version 44.3.0 from Synaptic. Linux mint had left me at version 43.0.
