### ISSUE TITLE
Nemo can’t open these old ZIP files

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/nemo-extensions#538]
### Distribution

Linux Mint Cinnamon 22

### Package version

6.2.6

### Frequency

Always

### Bug description

When I want to extract files from these ZIP archives with Nemo, I've got this error message:

![image](https://github.com/user-attachments/assets/736b17ce-aec4-446c-8ad1-0d521d96c29f)

See https://gitlab.gnome.org/GNOME/file-roller/-/issues/260

### Steps to reproduce

Click on one of theses files:

[AGATE.ZIP](https://github.com/user-attachments/files/16482490/AGATE.ZIP)
[BORIS.ZIP](https://github.com/user-attachments/files/16482491/BORIS.ZIP)
[CARIB24.ZIP](https://github.com/user-attachments/files/16482492/CARIB24.ZIP)
[PSWRD.ZIP](https://github.com/user-attachments/files/16482493/PSWRD.ZIP)
[TAPMKR20.ZIP](https://github.com/user-attachments/files/16482494/TAPMKR20.ZIP)

### Expected behavior

The archive should be opened.

**Comment by leigh123linux** [comment]
The issue doesn't reproduce on fedora.

```
[leigh@mpd-pc ~]$ rpm -qa *roller
file-roller-44.3-2.fc41.x86_64
nemo-fileroller-6.2.0-2.fc41.x86_64
[leigh@mpd-pc ~]$
```

**Comment by leigh123linux** [comment]
@InfoLibre  It's p7zip and 7zip that are broken not nemo.

```
$ /usr/bin/7za x '/home/leigh/Downloads/BORIS.ZIP' 

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_GB.UTF-8,Utf16=on,HugeFiles=on,64 bits,4 CPUs AMD Ryzen 3 4300U with Radeon Graphics          (860F01),ASM,AES-NI)

Scanning the drive for archives:
1 file, 83948 bytes (82 KiB)    

Extracting archive: /home/leigh/Downloads/BORIS.ZIP

ERRORS:
Headers Error

--
Path = /home/leigh/Downloads/BORIS.ZIP
Type = zip
ERRORS:
Headers Error
Physical Size = 83948

    

Archives with Errors: 1

Open Errors: 1

```

**Comment by InfoLibre** [comment]
Thank you. I made a report on 7z bugtracker.

**Comment by InfoLibre** [comment]
https://sourceforge.net/p/sevenzip/bugs/2517/
