### ISSUE TITLE
incorrect default-terminal-height  when nemo-terminal is placed at bottom

### ISSUE THREAD

**Issue by gbuntu127** [linuxmint/nemo-extensions#54]
Hi, thanks for the great tool. 

I managed to set the nemo-terminal to the bottom using org.nemo.extensions.nemo-terminal.terminal-position

However, the default-terminal-height is incorrect. When using default 5 lines, the terminal still takes about 20 lines in height. 

I am using gnome-shell flashback (compiz) in Ubuntu 14.04.
nemo-terminal version 1.0
nemo version 2.2.2

**Comment by iarroyo5** [comment]
Hello,
I'm the same problem in: Linux Mint 17 Qiana - version 14.04.3 LTS.

**Comment by brouillon** [comment]
Same here in linux mint 18.1 if nemo-terminal is set to bottom it will use all space available :(
Please allow us customize this extension see also #156 for color / background settings.

**Comment by NPuhlmann** [comment]
Same here with Linux Mint 18.3 .

**Comment by axelitus** [comment]
Same here using Ubuntu 18.04 and Nemo 3.6.5

**Comment by ViktorKovalev3** [comment]
Still bad. Up/\Up/\ Nemo 3.8.6 && NemoTerminal 3.8.2

**Comment by beguy** [comment]
Thx for fix. Wait it ver in official repo.
