### ISSUE TITLE
Disable beep sound for nemo-terminal

### ISSUE THREAD

**Issue by aungthurhahein** [linuxmint/nemo-extensions#66]
I just want to know how to disable beep sound from terminal. It's beeping all the time when folder change to another one.

**Comment by topotech** [comment]
Same here, I couldn't fix it by myself, and it's so annoying I should remove the package. I use Fedora 21 with Gnome 3.14

**Comment by oshawkat** [comment]
This is still an issue.  I would prefer to keep nemo-terminal displayed all the time but the beep occurs every time I change a folder so I either close nemo-terminal or mute my computer.

**Comment by Mailaender** [comment]
I can confirm that this is still an issue on version 3.0.0

**Comment by EduardDopler** [comment]
Could someone try editting the `nemo_terminal.py` in `/usr/share/nemo-python/extensions` (or wherever you have it) and exchange the following line [87]:
```python
self.term = Vte.Terminal()
```
with this:
```python
self.term = Vte.Terminal(audible_bell=False)
```

**Comment by Mailaender** [comment]
Seems to have no effect. Note: I am on Vte version 2.91 (openSUSE Tumbleweed).

**Comment by Ch3ck3r** [comment]
I came across this problem on Ubuntu 16.04 with cinnamon desktop today. @EduardDopler's fix is working for me. Thank you!

**Comment by Mailaender** [comment]
For me the problem has solved itself with an update.

**Comment by jctratt** [comment]
@EduardDopler's fix worked. Closing gui didn't fix, but type the command:
nemo -q && nemo
did fix it. Thank you @EduardDopler.
Note: on my computer, it takes about 30 seconds after closing nemo gui to get my command prompt back.
