### ISSUE TITLE
Removing nemo-terminal also removes gnome-terminal

### ISSUE THREAD

**Issue by bretkikehara** [linuxmint/nemo-extensions#93]
When I removed nemo-terminal, gnome-terminal also was removed. This will break the context menu's "Open in Terminal" option. This can be solved by reinstalling gnome-terminal.

**Temporary Fix:**
apt-get install gnome-terminal

**Comment by Rezonansowy** [comment]
It's only a workaround. But a change in nemo-terminal package dependencies may fix this.

**Comment by bretkikehara** [comment]
Exactly. I have added "temporary" to denote this.

Will updating [Nemo's Debian control](https://github.com/linuxmint/nemo/blob/master/debian/control) build dependencies will fix this problem? I am not too familiar with apt-get package control.

**Comment by Rezonansowy** [comment]
I think [nemo-terminal's Debian control](https://github.com/linuxmint/nemo-extensions/blob/master/nemo-terminal/debian/control) is the right file for these depends, but it seems to be fixed already. Does the problem still persists?

**Comment by monsta** [comment]
I can't reproduce it in LMDE 2 Betsy.

**Comment by GLolol** [comment]
I don't see anything wrong with either set of dependencies. What command are you using to uninstall things?

**Comment by leigh123linux** [comment]
Feel free to reopen if the issue still reproduces.
