### ISSUE TITLE
nemo-terminal is too responsive to F4

### ISSUE THREAD

**Issue by HifeFish** [linuxmint/nemo-extensions#98]
Closing a window via Alt+F4 in the process giving Nemo the focus will often trigger the terminal.
Even Ctrl+Alt+F4 will trigger the terminal, if you release Ctrl and Alt before F4.

**Comment by zorbama** [comment]
I confirm. When opening a file or folder properties, for example, and then closing it with Alt+F4, the terminal hides/unhides.
